# SASRec on MovieLens 1M — Full Rating Signal (1–5)

This notebook is a companion to `sasrec_movielens1m_positives.ipynb` and demonstrates
**full-signal** training using normalized 1–5 ratings as soft BCE labels.

## Key differences from the positives-only notebook

| | Positives-only (notebook 1) | Full-signal (this notebook) |
|---|---|---|
| Interactions used | Rating ≥ 4 only | All 1–5 ratings |
| OUTCOME | 1.0 (binary) | Rating/5 (0.2–1.0, soft label) |
| Estimator | `SASRecClassifierEstimator` (BCE) | `SASRecClassifierEstimator` (BCE, soft labels) |
| Random negatives | target = 0.0 | target = 0.0 (below any real interaction) |

## How soft-label BCE works

Instead of MSE on raw 1–5 ratings, we normalise to [0.2, 1.0] by dividing by 5.  
BCEWithLogitsLoss with soft targets [0, 1] pushes each item's score toward a value
whose sigmoid equals the normalised rating:

- Rating 5 → target 1.0 → score pushed high (most liked)
- Rating 1 → target 0.2 → score pushed slightly positive
- Random negative → target 0.0 → score pushed negative

This means **all interacted items score above all non-interacted items**, regardless of
rating, which directly optimises the HR@10 evaluation metric.  High-rated items also
score higher than low-rated ones, preserving the preference gradient.

## 1. Imports

In [1]:
import logging
import urllib.request
import zipfile
from pathlib import Path

import numpy as np
import pandas as pd

from skrec.dataset.interactions_dataset import InteractionsDataset
from skrec.dataset.items_dataset import ItemsDataset
from skrec.estimator.sequential import SASRecClassifierEstimator
from skrec.recommender.sequential import SequentialRecommender
from skrec.scorer.sequential import SequentialScorer

# Show training loss logs from the estimator
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(name)s %(levelname)s %(message)s")

RAW_DIR = Path("data/raw")
RAW_DIR.mkdir(parents=True, exist_ok=True)
DATA_DIR = Path("data/sasrec-ratings")
DATA_DIR.mkdir(parents=True, exist_ok=True)
print("Imports OK")

Imports OK

## 2. Download MovieLens 1M

Data is stored in `examples/movielens-1m/data/raw/` (excluded from git via `.gitignore`).  
If the files already exist from running notebook 1, this step is a no-op.

In [2]:
ML1M_URL = "https://files.grouplens.org/datasets/movielens/ml-1m.zip"
zip_path = RAW_DIR / "ml-1m.zip"

if not (RAW_DIR / "ratings.dat").exists():
    print("Downloading MovieLens 1M...")
    urllib.request.urlretrieve(ML1M_URL, zip_path)
    with zipfile.ZipFile(zip_path) as zf:
        for name in zf.namelist():
            if name.endswith(".dat"):
                filename = Path(name).name
                with zf.open(name) as src, open(RAW_DIR / filename, "wb") as dst:
                    dst.write(src.read())
    print("Downloaded and extracted.")
else:
    print("Already downloaded.")

Already downloaded.

## 3. Load and Preprocess — All Ratings as Soft Labels

Unlike the positives-only notebook, we keep **all 1M interactions**.  
OUTCOME is normalised to [0.2, 1.0] by dividing the raw rating by 5, so every real
interaction has a target **strictly above** the random-negative target of 0.0.  
Higher-rated items simply receive a stronger positive gradient.

In [3]:
# ratings.dat: UserID::MovieID::Rating::Timestamp
ratings = pd.read_csv(
    RAW_DIR / "ratings.dat",
    sep="::",
    engine="python",
    names=["UserID", "MovieID", "Rating", "Timestamp"],
)

# movies.dat: MovieID::Title::Genres
movies = pd.read_csv(
    RAW_DIR / "movies.dat",
    sep="::",
    engine="python",
    names=["MovieID", "Title", "Genres"],
    encoding="latin-1",
)

print(f"Ratings: {len(ratings):,}  |  Users: {ratings.UserID.nunique():,}  |  Movies: {ratings.MovieID.nunique():,}")
ratings.head()

Ratings: 1,000,209  |  Users: 6,040  |  Movies: 3,706

   UserID  MovieID  Rating  Timestamp
0       1     1193       5  978300760
1       1      661       3  978302109
2       1      914       3  978301968
3       1     3408       4  978300275
4       1     2355       5  978824291

In [4]:
# Map to library column names.
# OUTCOME: normalised rating (1.0–5.0) / 5 → soft label [0.2, 1.0].
# Random negatives sampled at training time will receive target=0.0,
# which is 1 unit below the worst real rating (1.0), giving the model a
# clear learned boundary: unseen < hated < ... < loved.
interactions = pd.DataFrame(
    {
        "USER_ID": ratings["UserID"].astype(str),
        "ITEM_ID": ratings["MovieID"].astype(str),
        "OUTCOME": ratings["Rating"].astype(float) / 5.0,  # 0.2, 0.4, 0.6, 0.8, or 1.0
        # Keep TIMESTAMP as int64 (not str) so sort is numeric, not lexicographic.
        # ML-1M timestamps span 9- and 10-digit values; string sort would order them wrong.
        "TIMESTAMP": ratings["Timestamp"],
    }
)

items = pd.DataFrame({"ITEM_ID": movies["MovieID"].astype(str)})

print(f"Total interactions: {len(interactions):,}")
interactions.head()

Total interactions: 1,000,209

  USER_ID ITEM_ID  OUTCOME  TIMESTAMP
0       1    1193      1.0  978300760
1       1     661      0.6  978302109
2       1     914      0.6  978301968
3       1    3408      0.8  978300275
4       1    2355      1.0  978824291

## 4. Rating Distribution

Unlike the positives-only notebook, our training sequences now contain the full
distribution of ratings. This section gives a feel for what the model will learn from.

In [5]:
rating_counts = ratings["Rating"].value_counts().sort_index()
print("Rating distribution (all interactions):")
print("=" * 40)
for rating, count in rating_counts.items():
    bar = "#" * (count // 10000)
    print(f"  {rating} stars: {count:>7,}  ({count / len(ratings):.1%})  {bar}")
print("=" * 40)
print(f"  Mean rating : {ratings['Rating'].mean():.2f}")
print(f"  Median      : {ratings['Rating'].median():.1f}")

Rating distribution (all interactions):
========================================
  1 stars:  56,174  (5.6%)  #####
  2 stars: 107,557  (10.8%)  ##########
  3 stars: 261,197  (26.1%)  ##########################
  4 stars: 348,971  (34.9%)  ##################################
  5 stars: 226,310  (22.6%)  ######################
========================================
  Mean rating : 3.58
  Median      : 4.0

## 5. Train / Test Split (Leave-Last-Out on All Interactions)

For each user, the interaction with the largest timestamp is the test item —
regardless of its rating. This is a stricter protocol than the positives-only
notebook: the model must predict the user's *next actual behavior*, not just
their next liked item.

Users with fewer than 5 total interactions are excluded.

In [6]:
# Sort by timestamp
interactions = interactions.sort_values(["USER_ID", "TIMESTAMP"]).reset_index(drop=True)

# Keep users with >= 5 interactions
user_counts = interactions.groupby("USER_ID").size()
valid_users = user_counts[user_counts >= 5].index
interactions = interactions[interactions["USER_ID"].isin(valid_users)].reset_index(drop=True)

# Rank items per user (0 = most recent = test)
interactions["rank"] = interactions.groupby("USER_ID").cumcount(ascending=False)
test_df = interactions[interactions["rank"] == 0].drop(columns=["rank"]).reset_index(drop=True)
valid_df = interactions[interactions["rank"] == 1].drop(columns=["rank"]).reset_index(drop=True)

# Training uses ALL interactions (matches original SASRec paper).
# The test item is used as the last training target: the model trains to predict it
# from the preceding history, which is exactly the task being evaluated.
train_df = interactions.drop(columns=["rank"]).reset_index(drop=True)

# Evaluation history: all interactions EXCEPT the test item.
all_except_test_df = interactions[interactions["rank"] >= 1].drop(columns=["rank"]).reset_index(drop=True)

print(f"Train interactions : {len(train_df):,}  (ALL interactions — test item used as last target)")
print(f"Valid interactions : {len(valid_df):,}  (one per user, for reference)")
print(f"Test  interactions : {len(test_df):,}  (one per user)")
print(f"Users              : {train_df.USER_ID.nunique():,}")
print()
print("Rating distribution of held-out test items:")
print(test_df["OUTCOME"].value_counts().sort_index().to_string())

Train interactions : 1,000,209  (ALL interactions — test item used as last target)
Valid interactions : 6,040  (one per user, for reference)
Test  interactions : 6,040  (one per user)
Users              : 6,040

Rating distribution of held-out test items:
OUTCOME
0.2     407
0.4     657
0.6    1413
0.8    1990
1.0    1573

## 6. Save CSVs and Create Datasets

In [7]:
train_path = str(DATA_DIR / "train_interactions.csv")
items_path = str(DATA_DIR / "items.csv")

# Train on ALL interactions (reference SASRec: test item is last training target per user)
if not Path(train_path).exists():
    train_df.to_csv(train_path, index=False)
if not Path(items_path).exists():
    items.to_csv(items_path, index=False)

interactions_ds = InteractionsDataset(data_location=train_path)
items_ds = ItemsDataset(data_location=items_path)

print(f"Training data: {len(train_df):,} interactions")
print("Datasets created.")

Training data: 1,000,209 interactions
Datasets created.

## 7. Build and Train SASRec (Classifier with Soft Labels)

We use `SASRecClassifierEstimator` (BCE) with soft labels and `num_negatives=1`.

**Why soft-label BCE?**  
BCEWithLogitsLoss natively supports targets in [0, 1].  Normalising ratings to
Rating/5 gives a graduated signal while keeping the loss bounded and well-conditioned.  
The model converges faster and learns more discriminative item embeddings than MSE on
raw 1–5 targets.

**Why `num_negatives=1`?**  
At each training step, one random unseen item is sampled with `target=0.0`.
Since the minimum normalised rating is 0.2, this creates a 0.2-unit gap that pushes
unseen items below even disliked ones — the core of the full-signal approach.

In [8]:
estimator = SASRecClassifierEstimator(
    hidden_units=50,
    num_blocks=2,
    num_heads=1,
    dropout_rate=0.2,
    num_negatives=1,  # original paper: 1 negative per step
    learning_rate=0.001,
    epochs=200,
    batch_size=128,
    optimizer_name="adam",
    loss_fn_name="bce",
    verbose=1,
)

scorer = SequentialScorer(estimator)
recommender = SequentialRecommender(scorer, max_len=200)

print("Training SASRec (soft-label BCE)...")
recommender.train(items_ds=items_ds, interactions_ds=interactions_ds)
print("Training complete.")

Training SASRec (soft-label BCE)...

2026-04-29 00:59:35,990 - skrec.recommender.sequential.sequential_recommender - WARNING SequentialRecommender.max_len=200 overrides SASRecClassifierEstimator.max_len=50. Pass the same max_len to both, or rely on the recommender's value.

2026-04-29 00:59:35,990 skrec.recommender.sequential.sequential_recommender WARNING SequentialRecommender.max_len=200 overrides SASRecClassifierEstimator.max_len=50. Pass the same max_len to both, or rely on the recommender's value.

2026-04-29 00:59:36,326 - skrec.recommender.sequential.sequential_recommender - INFO Built sequences for 6040 users (max_len=200, has_outcome=True).

2026-04-29 00:59:36,326 skrec.recommender.sequential.sequential_recommender INFO Built sequences for 6040 users (max_len=200, has_outcome=True).

2026-04-29 00:59:47,598 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [1/200], Loss: 1.1934

2026-04-29 00:59:47,598 skrec.estimator.sequential.sasrec_estimator INFO Epoch [1/200], Loss: 1.1934

2026-04-29 00:59:57,364 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [2/200], Loss: 1.0474

2026-04-29 00:59:57,364 skrec.estimator.sequential.sasrec_estimator INFO Epoch [2/200], Loss: 1.0474

2026-04-29 01:00:08,032 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [3/200], Loss: 1.0188

2026-04-29 01:00:08,032 skrec.estimator.sequential.sasrec_estimator INFO Epoch [3/200], Loss: 1.0188

2026-04-29 01:00:17,940 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [4/200], Loss: 0.9992

2026-04-29 01:00:17,940 skrec.estimator.sequential.sasrec_estimator INFO Epoch [4/200], Loss: 0.9992

2026-04-29 01:00:28,017 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [5/200], Loss: 0.9774

2026-04-29 01:00:28,017 skrec.estimator.sequential.sasrec_estimator INFO Epoch [5/200], Loss: 0.9774

2026-04-29 01:00:37,556 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [6/200], Loss: 0.9587

2026-04-29 01:00:37,556 skrec.estimator.sequential.sasrec_estimator INFO Epoch [6/200], Loss: 0.9587

2026-04-29 01:00:48,575 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [7/200], Loss: 0.9418

2026-04-29 01:00:48,575 skrec.estimator.sequential.sasrec_estimator INFO Epoch [7/200], Loss: 0.9418

2026-04-29 01:00:58,069 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [8/200], Loss: 0.9272

2026-04-29 01:00:58,069 skrec.estimator.sequential.sasrec_estimator INFO Epoch [8/200], Loss: 0.9272

2026-04-29 01:01:08,191 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [9/200], Loss: 0.9164

2026-04-29 01:01:08,191 skrec.estimator.sequential.sasrec_estimator INFO Epoch [9/200], Loss: 0.9164

2026-04-29 01:01:18,330 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [10/200], Loss: 0.9052

2026-04-29 01:01:18,330 skrec.estimator.sequential.sasrec_estimator INFO Epoch [10/200], Loss: 0.9052

2026-04-29 01:01:27,865 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [11/200], Loss: 0.8969

2026-04-29 01:01:27,865 skrec.estimator.sequential.sasrec_estimator INFO Epoch [11/200], Loss: 0.8969

2026-04-29 01:01:37,681 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [12/200], Loss: 0.8884

2026-04-29 01:01:37,681 skrec.estimator.sequential.sasrec_estimator INFO Epoch [12/200], Loss: 0.8884

2026-04-29 01:01:47,569 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [13/200], Loss: 0.8818

2026-04-29 01:01:47,569 skrec.estimator.sequential.sasrec_estimator INFO Epoch [13/200], Loss: 0.8818

2026-04-29 01:01:57,765 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [14/200], Loss: 0.8765

2026-04-29 01:01:57,765 skrec.estimator.sequential.sasrec_estimator INFO Epoch [14/200], Loss: 0.8765

2026-04-29 01:02:07,276 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [15/200], Loss: 0.8699

2026-04-29 01:02:07,276 skrec.estimator.sequential.sasrec_estimator INFO Epoch [15/200], Loss: 0.8699

2026-04-29 01:02:17,522 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [16/200], Loss: 0.8646

2026-04-29 01:02:17,522 skrec.estimator.sequential.sasrec_estimator INFO Epoch [16/200], Loss: 0.8646

2026-04-29 01:02:27,829 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [17/200], Loss: 0.8618

2026-04-29 01:02:27,829 skrec.estimator.sequential.sasrec_estimator INFO Epoch [17/200], Loss: 0.8618

2026-04-29 01:02:37,662 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [18/200], Loss: 0.8569

2026-04-29 01:02:37,662 skrec.estimator.sequential.sasrec_estimator INFO Epoch [18/200], Loss: 0.8569

2026-04-29 01:02:48,057 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [19/200], Loss: 0.8538

2026-04-29 01:02:48,057 skrec.estimator.sequential.sasrec_estimator INFO Epoch [19/200], Loss: 0.8538

2026-04-29 01:02:57,757 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [20/200], Loss: 0.8507

2026-04-29 01:02:57,757 skrec.estimator.sequential.sasrec_estimator INFO Epoch [20/200], Loss: 0.8507

2026-04-29 01:03:08,906 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [21/200], Loss: 0.8485

2026-04-29 01:03:08,906 skrec.estimator.sequential.sasrec_estimator INFO Epoch [21/200], Loss: 0.8485

2026-04-29 01:03:18,336 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [22/200], Loss: 0.8451

2026-04-29 01:03:18,336 skrec.estimator.sequential.sasrec_estimator INFO Epoch [22/200], Loss: 0.8451

2026-04-29 01:03:28,367 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [23/200], Loss: 0.8429

2026-04-29 01:03:28,367 skrec.estimator.sequential.sasrec_estimator INFO Epoch [23/200], Loss: 0.8429

2026-04-29 01:03:38,476 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [24/200], Loss: 0.8389

2026-04-29 01:03:38,476 skrec.estimator.sequential.sasrec_estimator INFO Epoch [24/200], Loss: 0.8389

2026-04-29 01:03:48,170 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [25/200], Loss: 0.8375

2026-04-29 01:03:48,170 skrec.estimator.sequential.sasrec_estimator INFO Epoch [25/200], Loss: 0.8375

2026-04-29 01:03:57,976 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [26/200], Loss: 0.8354

2026-04-29 01:03:57,976 skrec.estimator.sequential.sasrec_estimator INFO Epoch [26/200], Loss: 0.8354

2026-04-29 01:04:07,505 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [27/200], Loss: 0.8324

2026-04-29 01:04:07,505 skrec.estimator.sequential.sasrec_estimator INFO Epoch [27/200], Loss: 0.8324

2026-04-29 01:04:17,679 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [28/200], Loss: 0.8297

2026-04-29 01:04:17,679 skrec.estimator.sequential.sasrec_estimator INFO Epoch [28/200], Loss: 0.8297

2026-04-29 01:04:27,096 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [29/200], Loss: 0.8310

2026-04-29 01:04:27,096 skrec.estimator.sequential.sasrec_estimator INFO Epoch [29/200], Loss: 0.8310

2026-04-29 01:04:37,078 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [30/200], Loss: 0.8276

2026-04-29 01:04:37,078 skrec.estimator.sequential.sasrec_estimator INFO Epoch [30/200], Loss: 0.8276

2026-04-29 01:04:46,317 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [31/200], Loss: 0.8266

2026-04-29 01:04:46,317 skrec.estimator.sequential.sasrec_estimator INFO Epoch [31/200], Loss: 0.8266

2026-04-29 01:04:56,446 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [32/200], Loss: 0.8249

2026-04-29 01:04:56,446 skrec.estimator.sequential.sasrec_estimator INFO Epoch [32/200], Loss: 0.8249

2026-04-29 01:05:05,784 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [33/200], Loss: 0.8226

2026-04-29 01:05:05,784 skrec.estimator.sequential.sasrec_estimator INFO Epoch [33/200], Loss: 0.8226

2026-04-29 01:05:16,129 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [34/200], Loss: 0.8214

2026-04-29 01:05:16,129 skrec.estimator.sequential.sasrec_estimator INFO Epoch [34/200], Loss: 0.8214

2026-04-29 01:05:26,519 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [35/200], Loss: 0.8189

2026-04-29 01:05:26,519 skrec.estimator.sequential.sasrec_estimator INFO Epoch [35/200], Loss: 0.8189

2026-04-29 01:05:36,651 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [36/200], Loss: 0.8182

2026-04-29 01:05:36,651 skrec.estimator.sequential.sasrec_estimator INFO Epoch [36/200], Loss: 0.8182

2026-04-29 01:05:47,090 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [37/200], Loss: 0.8159

2026-04-29 01:05:47,090 skrec.estimator.sequential.sasrec_estimator INFO Epoch [37/200], Loss: 0.8159

2026-04-29 01:05:56,845 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [38/200], Loss: 0.8152

2026-04-29 01:05:56,845 skrec.estimator.sequential.sasrec_estimator INFO Epoch [38/200], Loss: 0.8152

2026-04-29 01:06:08,791 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [39/200], Loss: 0.8150

2026-04-29 01:06:08,791 skrec.estimator.sequential.sasrec_estimator INFO Epoch [39/200], Loss: 0.8150

2026-04-29 01:06:19,574 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [40/200], Loss: 0.8134

2026-04-29 01:06:19,574 skrec.estimator.sequential.sasrec_estimator INFO Epoch [40/200], Loss: 0.8134

2026-04-29 01:06:29,236 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [41/200], Loss: 0.8133

2026-04-29 01:06:29,236 skrec.estimator.sequential.sasrec_estimator INFO Epoch [41/200], Loss: 0.8133

2026-04-29 01:06:38,399 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [42/200], Loss: 0.8119

2026-04-29 01:06:38,399 skrec.estimator.sequential.sasrec_estimator INFO Epoch [42/200], Loss: 0.8119

2026-04-29 01:06:47,842 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [43/200], Loss: 0.8102

2026-04-29 01:06:47,842 skrec.estimator.sequential.sasrec_estimator INFO Epoch [43/200], Loss: 0.8102

2026-04-29 01:06:57,333 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [44/200], Loss: 0.8104

2026-04-29 01:06:57,333 skrec.estimator.sequential.sasrec_estimator INFO Epoch [44/200], Loss: 0.8104

2026-04-29 01:07:06,457 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [45/200], Loss: 0.8088

2026-04-29 01:07:06,457 skrec.estimator.sequential.sasrec_estimator INFO Epoch [45/200], Loss: 0.8088

2026-04-29 01:07:16,522 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [46/200], Loss: 0.8083

2026-04-29 01:07:16,522 skrec.estimator.sequential.sasrec_estimator INFO Epoch [46/200], Loss: 0.8083

2026-04-29 01:07:25,416 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [47/200], Loss: 0.8075

2026-04-29 01:07:25,416 skrec.estimator.sequential.sasrec_estimator INFO Epoch [47/200], Loss: 0.8075

2026-04-29 01:07:34,869 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [48/200], Loss: 0.8066

2026-04-29 01:07:34,869 skrec.estimator.sequential.sasrec_estimator INFO Epoch [48/200], Loss: 0.8066

2026-04-29 01:07:43,977 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [49/200], Loss: 0.8048

2026-04-29 01:07:43,977 skrec.estimator.sequential.sasrec_estimator INFO Epoch [49/200], Loss: 0.8048

2026-04-29 01:07:53,604 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [50/200], Loss: 0.8051

2026-04-29 01:07:53,604 skrec.estimator.sequential.sasrec_estimator INFO Epoch [50/200], Loss: 0.8051

2026-04-29 01:08:02,548 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [51/200], Loss: 0.8027

2026-04-29 01:08:02,548 skrec.estimator.sequential.sasrec_estimator INFO Epoch [51/200], Loss: 0.8027

2026-04-29 01:08:11,532 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [52/200], Loss: 0.8034

2026-04-29 01:08:11,532 skrec.estimator.sequential.sasrec_estimator INFO Epoch [52/200], Loss: 0.8034

2026-04-29 01:08:20,427 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [53/200], Loss: 0.8017

2026-04-29 01:08:20,427 skrec.estimator.sequential.sasrec_estimator INFO Epoch [53/200], Loss: 0.8017

2026-04-29 01:08:29,406 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [54/200], Loss: 0.8009

2026-04-29 01:08:29,406 skrec.estimator.sequential.sasrec_estimator INFO Epoch [54/200], Loss: 0.8009

2026-04-29 01:08:38,134 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [55/200], Loss: 0.8012

2026-04-29 01:08:38,134 skrec.estimator.sequential.sasrec_estimator INFO Epoch [55/200], Loss: 0.8012

2026-04-29 01:08:46,964 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [56/200], Loss: 0.8004

2026-04-29 01:08:46,964 skrec.estimator.sequential.sasrec_estimator INFO Epoch [56/200], Loss: 0.8004

2026-04-29 01:08:55,716 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [57/200], Loss: 0.7999

2026-04-29 01:08:55,716 skrec.estimator.sequential.sasrec_estimator INFO Epoch [57/200], Loss: 0.7999

2026-04-29 01:09:04,406 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [58/200], Loss: 0.7992

2026-04-29 01:09:04,406 skrec.estimator.sequential.sasrec_estimator INFO Epoch [58/200], Loss: 0.7992

2026-04-29 01:09:13,247 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [59/200], Loss: 0.7987

2026-04-29 01:09:13,247 skrec.estimator.sequential.sasrec_estimator INFO Epoch [59/200], Loss: 0.7987

2026-04-29 01:09:22,164 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [60/200], Loss: 0.7973

2026-04-29 01:09:22,164 skrec.estimator.sequential.sasrec_estimator INFO Epoch [60/200], Loss: 0.7973

2026-04-29 01:09:30,983 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [61/200], Loss: 0.7962

2026-04-29 01:09:30,983 skrec.estimator.sequential.sasrec_estimator INFO Epoch [61/200], Loss: 0.7962

2026-04-29 01:09:39,604 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [62/200], Loss: 0.7968

2026-04-29 01:09:39,604 skrec.estimator.sequential.sasrec_estimator INFO Epoch [62/200], Loss: 0.7968

2026-04-29 01:09:48,590 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [63/200], Loss: 0.7958

2026-04-29 01:09:48,590 skrec.estimator.sequential.sasrec_estimator INFO Epoch [63/200], Loss: 0.7958

2026-04-29 01:09:57,345 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [64/200], Loss: 0.7953

2026-04-29 01:09:57,345 skrec.estimator.sequential.sasrec_estimator INFO Epoch [64/200], Loss: 0.7953

2026-04-29 01:10:06,113 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [65/200], Loss: 0.7963

2026-04-29 01:10:06,113 skrec.estimator.sequential.sasrec_estimator INFO Epoch [65/200], Loss: 0.7963

2026-04-29 01:10:14,908 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [66/200], Loss: 0.7950

2026-04-29 01:10:14,908 skrec.estimator.sequential.sasrec_estimator INFO Epoch [66/200], Loss: 0.7950

2026-04-29 01:10:24,062 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [67/200], Loss: 0.7941

2026-04-29 01:10:24,062 skrec.estimator.sequential.sasrec_estimator INFO Epoch [67/200], Loss: 0.7941

2026-04-29 01:10:33,100 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [68/200], Loss: 0.7931

2026-04-29 01:10:33,100 skrec.estimator.sequential.sasrec_estimator INFO Epoch [68/200], Loss: 0.7931

2026-04-29 01:10:42,178 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [69/200], Loss: 0.7931

2026-04-29 01:10:42,178 skrec.estimator.sequential.sasrec_estimator INFO Epoch [69/200], Loss: 0.7931

2026-04-29 01:10:51,318 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [70/200], Loss: 0.7928

2026-04-29 01:10:51,318 skrec.estimator.sequential.sasrec_estimator INFO Epoch [70/200], Loss: 0.7928

2026-04-29 01:11:00,115 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [71/200], Loss: 0.7930

2026-04-29 01:11:00,115 skrec.estimator.sequential.sasrec_estimator INFO Epoch [71/200], Loss: 0.7930

2026-04-29 01:11:09,004 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [72/200], Loss: 0.7923

2026-04-29 01:11:09,004 skrec.estimator.sequential.sasrec_estimator INFO Epoch [72/200], Loss: 0.7923

2026-04-29 01:11:17,669 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [73/200], Loss: 0.7926

2026-04-29 01:11:17,669 skrec.estimator.sequential.sasrec_estimator INFO Epoch [73/200], Loss: 0.7926

2026-04-29 01:11:26,269 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [74/200], Loss: 0.7911

2026-04-29 01:11:26,269 skrec.estimator.sequential.sasrec_estimator INFO Epoch [74/200], Loss: 0.7911

2026-04-29 01:11:35,068 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [75/200], Loss: 0.7906

2026-04-29 01:11:35,068 skrec.estimator.sequential.sasrec_estimator INFO Epoch [75/200], Loss: 0.7906

2026-04-29 01:11:43,829 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [76/200], Loss: 0.7907

2026-04-29 01:11:43,829 skrec.estimator.sequential.sasrec_estimator INFO Epoch [76/200], Loss: 0.7907

2026-04-29 01:11:52,791 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [77/200], Loss: 0.7897

2026-04-29 01:11:52,791 skrec.estimator.sequential.sasrec_estimator INFO Epoch [77/200], Loss: 0.7897

2026-04-29 01:12:01,697 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [78/200], Loss: 0.7894

2026-04-29 01:12:01,697 skrec.estimator.sequential.sasrec_estimator INFO Epoch [78/200], Loss: 0.7894

2026-04-29 01:12:10,700 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [79/200], Loss: 0.7895

2026-04-29 01:12:10,700 skrec.estimator.sequential.sasrec_estimator INFO Epoch [79/200], Loss: 0.7895

2026-04-29 01:12:19,588 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [80/200], Loss: 0.7887

2026-04-29 01:12:19,588 skrec.estimator.sequential.sasrec_estimator INFO Epoch [80/200], Loss: 0.7887

2026-04-29 01:12:28,609 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [81/200], Loss: 0.7888

2026-04-29 01:12:28,609 skrec.estimator.sequential.sasrec_estimator INFO Epoch [81/200], Loss: 0.7888

2026-04-29 01:12:37,544 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [82/200], Loss: 0.7892

2026-04-29 01:12:37,544 skrec.estimator.sequential.sasrec_estimator INFO Epoch [82/200], Loss: 0.7892

2026-04-29 01:12:46,062 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [83/200], Loss: 0.7882

2026-04-29 01:12:46,062 skrec.estimator.sequential.sasrec_estimator INFO Epoch [83/200], Loss: 0.7882

2026-04-29 01:12:54,849 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [84/200], Loss: 0.7878

2026-04-29 01:12:54,849 skrec.estimator.sequential.sasrec_estimator INFO Epoch [84/200], Loss: 0.7878

2026-04-29 01:13:03,680 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [85/200], Loss: 0.7868

2026-04-29 01:13:03,680 skrec.estimator.sequential.sasrec_estimator INFO Epoch [85/200], Loss: 0.7868

2026-04-29 01:13:12,756 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [86/200], Loss: 0.7874

2026-04-29 01:13:12,756 skrec.estimator.sequential.sasrec_estimator INFO Epoch [86/200], Loss: 0.7874

2026-04-29 01:13:21,434 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [87/200], Loss: 0.7859

2026-04-29 01:13:21,434 skrec.estimator.sequential.sasrec_estimator INFO Epoch [87/200], Loss: 0.7859

2026-04-29 01:13:30,228 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [88/200], Loss: 0.7863

2026-04-29 01:13:30,228 skrec.estimator.sequential.sasrec_estimator INFO Epoch [88/200], Loss: 0.7863

2026-04-29 01:13:38,944 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [89/200], Loss: 0.7871

2026-04-29 01:13:38,944 skrec.estimator.sequential.sasrec_estimator INFO Epoch [89/200], Loss: 0.7871

2026-04-29 01:13:47,753 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [90/200], Loss: 0.7867

2026-04-29 01:13:47,753 skrec.estimator.sequential.sasrec_estimator INFO Epoch [90/200], Loss: 0.7867

2026-04-29 01:13:56,727 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [91/200], Loss: 0.7863

2026-04-29 01:13:56,727 skrec.estimator.sequential.sasrec_estimator INFO Epoch [91/200], Loss: 0.7863

2026-04-29 01:14:05,608 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [92/200], Loss: 0.7848

2026-04-29 01:14:05,608 skrec.estimator.sequential.sasrec_estimator INFO Epoch [92/200], Loss: 0.7848

2026-04-29 01:14:14,593 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [93/200], Loss: 0.7852

2026-04-29 01:14:14,593 skrec.estimator.sequential.sasrec_estimator INFO Epoch [93/200], Loss: 0.7852

2026-04-29 01:14:23,388 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [94/200], Loss: 0.7847

2026-04-29 01:14:23,388 skrec.estimator.sequential.sasrec_estimator INFO Epoch [94/200], Loss: 0.7847

2026-04-29 01:14:32,386 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [95/200], Loss: 0.7837

2026-04-29 01:14:32,386 skrec.estimator.sequential.sasrec_estimator INFO Epoch [95/200], Loss: 0.7837

2026-04-29 01:14:41,214 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [96/200], Loss: 0.7841

2026-04-29 01:14:41,214 skrec.estimator.sequential.sasrec_estimator INFO Epoch [96/200], Loss: 0.7841

2026-04-29 01:14:50,175 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [97/200], Loss: 0.7838

2026-04-29 01:14:50,175 skrec.estimator.sequential.sasrec_estimator INFO Epoch [97/200], Loss: 0.7838

2026-04-29 01:14:59,030 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [98/200], Loss: 0.7834

2026-04-29 01:14:59,030 skrec.estimator.sequential.sasrec_estimator INFO Epoch [98/200], Loss: 0.7834

2026-04-29 01:15:07,821 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [99/200], Loss: 0.7826

2026-04-29 01:15:07,821 skrec.estimator.sequential.sasrec_estimator INFO Epoch [99/200], Loss: 0.7826

2026-04-29 01:15:16,862 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [100/200], Loss: 0.7839

2026-04-29 01:15:16,862 skrec.estimator.sequential.sasrec_estimator INFO Epoch [100/200], Loss: 0.7839

2026-04-29 01:15:25,513 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [101/200], Loss: 0.7831

2026-04-29 01:15:25,513 skrec.estimator.sequential.sasrec_estimator INFO Epoch [101/200], Loss: 0.7831

2026-04-29 01:15:34,291 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [102/200], Loss: 0.7831

2026-04-29 01:15:34,291 skrec.estimator.sequential.sasrec_estimator INFO Epoch [102/200], Loss: 0.7831

2026-04-29 01:15:42,898 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [103/200], Loss: 0.7830

2026-04-29 01:15:42,898 skrec.estimator.sequential.sasrec_estimator INFO Epoch [103/200], Loss: 0.7830

2026-04-29 01:15:51,890 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [104/200], Loss: 0.7819

2026-04-29 01:15:51,890 skrec.estimator.sequential.sasrec_estimator INFO Epoch [104/200], Loss: 0.7819

2026-04-29 01:16:00,955 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [105/200], Loss: 0.7824

2026-04-29 01:16:00,955 skrec.estimator.sequential.sasrec_estimator INFO Epoch [105/200], Loss: 0.7824

2026-04-29 01:16:09,820 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [106/200], Loss: 0.7831

2026-04-29 01:16:09,820 skrec.estimator.sequential.sasrec_estimator INFO Epoch [106/200], Loss: 0.7831

2026-04-29 01:16:18,547 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [107/200], Loss: 0.7817

2026-04-29 01:16:18,547 skrec.estimator.sequential.sasrec_estimator INFO Epoch [107/200], Loss: 0.7817

2026-04-29 01:16:27,213 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [108/200], Loss: 0.7816

2026-04-29 01:16:27,213 skrec.estimator.sequential.sasrec_estimator INFO Epoch [108/200], Loss: 0.7816

2026-04-29 01:16:36,203 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [109/200], Loss: 0.7821

2026-04-29 01:16:36,203 skrec.estimator.sequential.sasrec_estimator INFO Epoch [109/200], Loss: 0.7821

2026-04-29 01:16:45,129 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [110/200], Loss: 0.7809

2026-04-29 01:16:45,129 skrec.estimator.sequential.sasrec_estimator INFO Epoch [110/200], Loss: 0.7809

2026-04-29 01:16:53,748 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [111/200], Loss: 0.7810

2026-04-29 01:16:53,748 skrec.estimator.sequential.sasrec_estimator INFO Epoch [111/200], Loss: 0.7810

2026-04-29 01:17:02,819 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [112/200], Loss: 0.7807

2026-04-29 01:17:02,819 skrec.estimator.sequential.sasrec_estimator INFO Epoch [112/200], Loss: 0.7807

2026-04-29 01:17:12,029 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [113/200], Loss: 0.7809

2026-04-29 01:17:12,029 skrec.estimator.sequential.sasrec_estimator INFO Epoch [113/200], Loss: 0.7809

2026-04-29 01:17:21,146 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [114/200], Loss: 0.7801

2026-04-29 01:17:21,146 skrec.estimator.sequential.sasrec_estimator INFO Epoch [114/200], Loss: 0.7801

2026-04-29 01:17:30,246 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [115/200], Loss: 0.7800

2026-04-29 01:17:30,246 skrec.estimator.sequential.sasrec_estimator INFO Epoch [115/200], Loss: 0.7800

2026-04-29 01:17:39,319 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [116/200], Loss: 0.7812

2026-04-29 01:17:39,319 skrec.estimator.sequential.sasrec_estimator INFO Epoch [116/200], Loss: 0.7812

2026-04-29 01:17:47,992 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [117/200], Loss: 0.7786

2026-04-29 01:17:47,992 skrec.estimator.sequential.sasrec_estimator INFO Epoch [117/200], Loss: 0.7786

2026-04-29 01:17:56,914 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [118/200], Loss: 0.7802

2026-04-29 01:17:56,914 skrec.estimator.sequential.sasrec_estimator INFO Epoch [118/200], Loss: 0.7802

2026-04-29 01:18:05,924 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [119/200], Loss: 0.7789

2026-04-29 01:18:05,924 skrec.estimator.sequential.sasrec_estimator INFO Epoch [119/200], Loss: 0.7789

2026-04-29 01:18:14,749 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [120/200], Loss: 0.7799

2026-04-29 01:18:14,749 skrec.estimator.sequential.sasrec_estimator INFO Epoch [120/200], Loss: 0.7799

2026-04-29 01:18:23,676 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [121/200], Loss: 0.7800

2026-04-29 01:18:23,676 skrec.estimator.sequential.sasrec_estimator INFO Epoch [121/200], Loss: 0.7800

2026-04-29 01:18:32,800 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [122/200], Loss: 0.7795

2026-04-29 01:18:32,800 skrec.estimator.sequential.sasrec_estimator INFO Epoch [122/200], Loss: 0.7795

2026-04-29 01:18:41,939 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [123/200], Loss: 0.7799

2026-04-29 01:18:41,939 skrec.estimator.sequential.sasrec_estimator INFO Epoch [123/200], Loss: 0.7799

2026-04-29 01:18:50,930 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [124/200], Loss: 0.7792

2026-04-29 01:18:50,930 skrec.estimator.sequential.sasrec_estimator INFO Epoch [124/200], Loss: 0.7792

2026-04-29 01:18:59,672 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [125/200], Loss: 0.7793

2026-04-29 01:18:59,672 skrec.estimator.sequential.sasrec_estimator INFO Epoch [125/200], Loss: 0.7793

2026-04-29 01:19:08,633 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [126/200], Loss: 0.7799

2026-04-29 01:19:08,633 skrec.estimator.sequential.sasrec_estimator INFO Epoch [126/200], Loss: 0.7799

2026-04-29 01:19:17,476 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [127/200], Loss: 0.7781

2026-04-29 01:19:17,476 skrec.estimator.sequential.sasrec_estimator INFO Epoch [127/200], Loss: 0.7781

2026-04-29 01:19:26,251 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [128/200], Loss: 0.7776

2026-04-29 01:19:26,251 skrec.estimator.sequential.sasrec_estimator INFO Epoch [128/200], Loss: 0.7776

2026-04-29 01:19:34,206 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [129/200], Loss: 0.7779

2026-04-29 01:19:34,206 skrec.estimator.sequential.sasrec_estimator INFO Epoch [129/200], Loss: 0.7779

2026-04-29 01:19:41,997 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [130/200], Loss: 0.7782

2026-04-29 01:19:41,997 skrec.estimator.sequential.sasrec_estimator INFO Epoch [130/200], Loss: 0.7782

2026-04-29 01:19:49,736 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [131/200], Loss: 0.7777

2026-04-29 01:19:49,736 skrec.estimator.sequential.sasrec_estimator INFO Epoch [131/200], Loss: 0.7777

2026-04-29 01:19:57,442 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [132/200], Loss: 0.7773

2026-04-29 01:19:57,442 skrec.estimator.sequential.sasrec_estimator INFO Epoch [132/200], Loss: 0.7773

2026-04-29 01:20:05,168 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [133/200], Loss: 0.7767

2026-04-29 01:20:05,168 skrec.estimator.sequential.sasrec_estimator INFO Epoch [133/200], Loss: 0.7767

2026-04-29 01:20:12,987 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [134/200], Loss: 0.7770

2026-04-29 01:20:12,987 skrec.estimator.sequential.sasrec_estimator INFO Epoch [134/200], Loss: 0.7770

2026-04-29 01:20:20,916 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [135/200], Loss: 0.7783

2026-04-29 01:20:20,916 skrec.estimator.sequential.sasrec_estimator INFO Epoch [135/200], Loss: 0.7783

2026-04-29 01:20:28,809 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [136/200], Loss: 0.7773

2026-04-29 01:20:28,809 skrec.estimator.sequential.sasrec_estimator INFO Epoch [136/200], Loss: 0.7773

2026-04-29 01:20:36,679 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [137/200], Loss: 0.7775

2026-04-29 01:20:36,679 skrec.estimator.sequential.sasrec_estimator INFO Epoch [137/200], Loss: 0.7775

2026-04-29 01:20:44,483 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [138/200], Loss: 0.7776

2026-04-29 01:20:44,483 skrec.estimator.sequential.sasrec_estimator INFO Epoch [138/200], Loss: 0.7776

2026-04-29 01:20:51,874 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [139/200], Loss: 0.7775

2026-04-29 01:20:51,874 skrec.estimator.sequential.sasrec_estimator INFO Epoch [139/200], Loss: 0.7775

2026-04-29 01:20:59,260 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [140/200], Loss: 0.7765

2026-04-29 01:20:59,260 skrec.estimator.sequential.sasrec_estimator INFO Epoch [140/200], Loss: 0.7765

2026-04-29 01:21:06,434 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [141/200], Loss: 0.7764

2026-04-29 01:21:06,434 skrec.estimator.sequential.sasrec_estimator INFO Epoch [141/200], Loss: 0.7764

2026-04-29 01:21:13,667 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [142/200], Loss: 0.7785

2026-04-29 01:21:13,667 skrec.estimator.sequential.sasrec_estimator INFO Epoch [142/200], Loss: 0.7785

2026-04-29 01:21:20,836 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [143/200], Loss: 0.7758

2026-04-29 01:21:20,836 skrec.estimator.sequential.sasrec_estimator INFO Epoch [143/200], Loss: 0.7758

2026-04-29 01:21:28,005 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [144/200], Loss: 0.7754

2026-04-29 01:21:28,005 skrec.estimator.sequential.sasrec_estimator INFO Epoch [144/200], Loss: 0.7754

2026-04-29 01:21:35,182 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [145/200], Loss: 0.7762

2026-04-29 01:21:35,182 skrec.estimator.sequential.sasrec_estimator INFO Epoch [145/200], Loss: 0.7762

2026-04-29 01:21:42,358 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [146/200], Loss: 0.7752

2026-04-29 01:21:42,358 skrec.estimator.sequential.sasrec_estimator INFO Epoch [146/200], Loss: 0.7752

2026-04-29 01:21:49,563 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [147/200], Loss: 0.7773

2026-04-29 01:21:49,563 skrec.estimator.sequential.sasrec_estimator INFO Epoch [147/200], Loss: 0.7773

2026-04-29 01:21:56,748 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [148/200], Loss: 0.7761

2026-04-29 01:21:56,748 skrec.estimator.sequential.sasrec_estimator INFO Epoch [148/200], Loss: 0.7761

2026-04-29 01:22:03,851 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [149/200], Loss: 0.7754

2026-04-29 01:22:03,851 skrec.estimator.sequential.sasrec_estimator INFO Epoch [149/200], Loss: 0.7754

2026-04-29 01:22:10,915 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [150/200], Loss: 0.7760

2026-04-29 01:22:10,915 skrec.estimator.sequential.sasrec_estimator INFO Epoch [150/200], Loss: 0.7760

2026-04-29 01:22:17,962 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [151/200], Loss: 0.7761

2026-04-29 01:22:17,962 skrec.estimator.sequential.sasrec_estimator INFO Epoch [151/200], Loss: 0.7761

2026-04-29 01:22:25,063 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [152/200], Loss: 0.7761

2026-04-29 01:22:25,063 skrec.estimator.sequential.sasrec_estimator INFO Epoch [152/200], Loss: 0.7761

2026-04-29 01:22:32,227 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [153/200], Loss: 0.7755

2026-04-29 01:22:32,227 skrec.estimator.sequential.sasrec_estimator INFO Epoch [153/200], Loss: 0.7755

2026-04-29 01:22:39,396 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [154/200], Loss: 0.7752

2026-04-29 01:22:39,396 skrec.estimator.sequential.sasrec_estimator INFO Epoch [154/200], Loss: 0.7752

2026-04-29 01:22:46,557 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [155/200], Loss: 0.7755

2026-04-29 01:22:46,557 skrec.estimator.sequential.sasrec_estimator INFO Epoch [155/200], Loss: 0.7755

2026-04-29 01:22:53,710 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [156/200], Loss: 0.7744

2026-04-29 01:22:53,710 skrec.estimator.sequential.sasrec_estimator INFO Epoch [156/200], Loss: 0.7744

2026-04-29 01:23:00,865 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [157/200], Loss: 0.7736

2026-04-29 01:23:00,865 skrec.estimator.sequential.sasrec_estimator INFO Epoch [157/200], Loss: 0.7736

2026-04-29 01:23:07,976 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [158/200], Loss: 0.7747

2026-04-29 01:23:07,976 skrec.estimator.sequential.sasrec_estimator INFO Epoch [158/200], Loss: 0.7747

2026-04-29 01:23:15,007 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [159/200], Loss: 0.7731

2026-04-29 01:23:15,007 skrec.estimator.sequential.sasrec_estimator INFO Epoch [159/200], Loss: 0.7731

2026-04-29 01:23:21,991 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [160/200], Loss: 0.7728

2026-04-29 01:23:21,991 skrec.estimator.sequential.sasrec_estimator INFO Epoch [160/200], Loss: 0.7728

2026-04-29 01:23:28,966 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [161/200], Loss: 0.7746

2026-04-29 01:23:28,966 skrec.estimator.sequential.sasrec_estimator INFO Epoch [161/200], Loss: 0.7746

2026-04-29 01:23:35,951 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [162/200], Loss: 0.7745

2026-04-29 01:23:35,951 skrec.estimator.sequential.sasrec_estimator INFO Epoch [162/200], Loss: 0.7745

2026-04-29 01:23:43,118 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [163/200], Loss: 0.7743

2026-04-29 01:23:43,118 skrec.estimator.sequential.sasrec_estimator INFO Epoch [163/200], Loss: 0.7743

2026-04-29 01:23:50,242 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [164/200], Loss: 0.7745

2026-04-29 01:23:50,242 skrec.estimator.sequential.sasrec_estimator INFO Epoch [164/200], Loss: 0.7745

2026-04-29 01:23:57,372 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [165/200], Loss: 0.7733

2026-04-29 01:23:57,372 skrec.estimator.sequential.sasrec_estimator INFO Epoch [165/200], Loss: 0.7733

2026-04-29 01:24:04,515 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [166/200], Loss: 0.7743

2026-04-29 01:24:04,515 skrec.estimator.sequential.sasrec_estimator INFO Epoch [166/200], Loss: 0.7743

2026-04-29 01:24:11,757 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [167/200], Loss: 0.7742

2026-04-29 01:24:11,757 skrec.estimator.sequential.sasrec_estimator INFO Epoch [167/200], Loss: 0.7742

2026-04-29 01:24:18,961 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [168/200], Loss: 0.7738

2026-04-29 01:24:18,961 skrec.estimator.sequential.sasrec_estimator INFO Epoch [168/200], Loss: 0.7738

2026-04-29 01:24:25,981 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [169/200], Loss: 0.7729

2026-04-29 01:24:25,981 skrec.estimator.sequential.sasrec_estimator INFO Epoch [169/200], Loss: 0.7729

2026-04-29 01:24:32,987 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [170/200], Loss: 0.7740

2026-04-29 01:24:32,987 skrec.estimator.sequential.sasrec_estimator INFO Epoch [170/200], Loss: 0.7740

2026-04-29 01:24:40,110 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [171/200], Loss: 0.7728

2026-04-29 01:24:40,110 skrec.estimator.sequential.sasrec_estimator INFO Epoch [171/200], Loss: 0.7728

2026-04-29 01:24:47,135 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [172/200], Loss: 0.7733

2026-04-29 01:24:47,135 skrec.estimator.sequential.sasrec_estimator INFO Epoch [172/200], Loss: 0.7733

2026-04-29 01:24:54,097 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [173/200], Loss: 0.7732

2026-04-29 01:24:54,097 skrec.estimator.sequential.sasrec_estimator INFO Epoch [173/200], Loss: 0.7732

2026-04-29 01:25:01,087 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [174/200], Loss: 0.7731

2026-04-29 01:25:01,087 skrec.estimator.sequential.sasrec_estimator INFO Epoch [174/200], Loss: 0.7731

2026-04-29 01:25:08,072 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [175/200], Loss: 0.7736

2026-04-29 01:25:08,072 skrec.estimator.sequential.sasrec_estimator INFO Epoch [175/200], Loss: 0.7736

2026-04-29 01:25:15,028 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [176/200], Loss: 0.7728

2026-04-29 01:25:15,028 skrec.estimator.sequential.sasrec_estimator INFO Epoch [176/200], Loss: 0.7728

2026-04-29 01:25:22,032 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [177/200], Loss: 0.7741

2026-04-29 01:25:22,032 skrec.estimator.sequential.sasrec_estimator INFO Epoch [177/200], Loss: 0.7741

2026-04-29 01:25:29,074 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [178/200], Loss: 0.7728

2026-04-29 01:25:29,074 skrec.estimator.sequential.sasrec_estimator INFO Epoch [178/200], Loss: 0.7728

2026-04-29 01:25:36,056 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [179/200], Loss: 0.7724

2026-04-29 01:25:36,056 skrec.estimator.sequential.sasrec_estimator INFO Epoch [179/200], Loss: 0.7724

2026-04-29 01:25:43,039 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [180/200], Loss: 0.7714

2026-04-29 01:25:43,039 skrec.estimator.sequential.sasrec_estimator INFO Epoch [180/200], Loss: 0.7714

2026-04-29 01:25:50,182 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [181/200], Loss: 0.7725

2026-04-29 01:25:50,182 skrec.estimator.sequential.sasrec_estimator INFO Epoch [181/200], Loss: 0.7725

2026-04-29 01:25:57,355 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [182/200], Loss: 0.7731

2026-04-29 01:25:57,355 skrec.estimator.sequential.sasrec_estimator INFO Epoch [182/200], Loss: 0.7731

2026-04-29 01:26:04,529 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [183/200], Loss: 0.7720

2026-04-29 01:26:04,529 skrec.estimator.sequential.sasrec_estimator INFO Epoch [183/200], Loss: 0.7720

2026-04-29 01:26:11,682 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [184/200], Loss: 0.7730

2026-04-29 01:26:11,682 skrec.estimator.sequential.sasrec_estimator INFO Epoch [184/200], Loss: 0.7730

2026-04-29 01:26:18,610 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [185/200], Loss: 0.7723

2026-04-29 01:26:18,610 skrec.estimator.sequential.sasrec_estimator INFO Epoch [185/200], Loss: 0.7723

2026-04-29 01:26:25,604 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [186/200], Loss: 0.7719

2026-04-29 01:26:25,604 skrec.estimator.sequential.sasrec_estimator INFO Epoch [186/200], Loss: 0.7719

2026-04-29 01:26:32,539 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [187/200], Loss: 0.7721

2026-04-29 01:26:32,539 skrec.estimator.sequential.sasrec_estimator INFO Epoch [187/200], Loss: 0.7721

2026-04-29 01:26:39,550 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [188/200], Loss: 0.7719

2026-04-29 01:26:39,550 skrec.estimator.sequential.sasrec_estimator INFO Epoch [188/200], Loss: 0.7719

2026-04-29 01:26:46,674 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [189/200], Loss: 0.7722

2026-04-29 01:26:46,674 skrec.estimator.sequential.sasrec_estimator INFO Epoch [189/200], Loss: 0.7722

2026-04-29 01:26:53,897 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [190/200], Loss: 0.7724

2026-04-29 01:26:53,897 skrec.estimator.sequential.sasrec_estimator INFO Epoch [190/200], Loss: 0.7724

2026-04-29 01:27:01,059 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [191/200], Loss: 0.7721

2026-04-29 01:27:01,059 skrec.estimator.sequential.sasrec_estimator INFO Epoch [191/200], Loss: 0.7721

2026-04-29 01:27:08,120 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [192/200], Loss: 0.7723

2026-04-29 01:27:08,120 skrec.estimator.sequential.sasrec_estimator INFO Epoch [192/200], Loss: 0.7723

2026-04-29 01:27:15,309 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [193/200], Loss: 0.7717

2026-04-29 01:27:15,309 skrec.estimator.sequential.sasrec_estimator INFO Epoch [193/200], Loss: 0.7717

2026-04-29 01:27:22,418 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [194/200], Loss: 0.7722

2026-04-29 01:27:22,418 skrec.estimator.sequential.sasrec_estimator INFO Epoch [194/200], Loss: 0.7722

2026-04-29 01:27:29,559 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [195/200], Loss: 0.7715

2026-04-29 01:27:29,559 skrec.estimator.sequential.sasrec_estimator INFO Epoch [195/200], Loss: 0.7715

2026-04-29 01:27:36,796 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [196/200], Loss: 0.7721

2026-04-29 01:27:36,796 skrec.estimator.sequential.sasrec_estimator INFO Epoch [196/200], Loss: 0.7721

2026-04-29 01:27:43,962 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [197/200], Loss: 0.7721

2026-04-29 01:27:43,962 skrec.estimator.sequential.sasrec_estimator INFO Epoch [197/200], Loss: 0.7721

2026-04-29 01:27:51,123 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [198/200], Loss: 0.7714

2026-04-29 01:27:51,123 skrec.estimator.sequential.sasrec_estimator INFO Epoch [198/200], Loss: 0.7714

2026-04-29 01:27:58,270 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [199/200], Loss: 0.7719

2026-04-29 01:27:58,270 skrec.estimator.sequential.sasrec_estimator INFO Epoch [199/200], Loss: 0.7719

2026-04-29 01:28:05,433 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [200/200], Loss: 0.7707

2026-04-29 01:28:05,433 skrec.estimator.sequential.sasrec_estimator INFO Epoch [200/200], Loss: 0.7707

Training complete.

## 8. Evaluate: HR@10 and NDCG@10

Same leave-last-out evaluation as notebook 1. The held-out item may have any
rating (1–5) — we check only whether it appears in the top-10, not whether it
was liked. This tests how well the model predicts the user's *next action*.

User order is anchored to `_build_sequences` output to guarantee row alignment
with `recommend()`.

In [9]:
rng = np.random.default_rng(42)
all_item_ids = np.array(list(scorer.item_names))

known_items = set(scorer.item_names)
eval_test_df = test_df[test_df["ITEM_ID"].isin(known_items)].copy()
eval_users = set(eval_test_df["USER_ID"])

# Evaluation history: all interactions EXCEPT the test item.
# The model's last-position representation was trained to predict the test item
# from exactly this context.
eval_history_df = all_except_test_df[all_except_test_df["USER_ID"].isin(eval_users)].copy()
eval_history_df = eval_history_df.sort_values(["USER_ID", "TIMESTAMP"]).reset_index(drop=True)

print(f"Evaluating {len(eval_users):,} users (sampled ranking: 1 positive + 100 negatives)...")

sequences_df = recommender._build_sequences(eval_history_df)
user_order = sequences_df["USER_ID"].tolist()

# Get all-item scores once: (num_users, num_items)
all_scores = recommender.scorer.estimator.predict_proba_with_embeddings(interactions=sequences_df)
item_name_to_idx = {name: i for i, name in enumerate(scorer.item_names)}

gt_lookup = eval_test_df.set_index("USER_ID")["ITEM_ID"].to_dict()
user_items = interactions.groupby("USER_ID")["ITEM_ID"].apply(set).to_dict()

TOP_K = 10
N_NEGATIVES = 100

hits, ndcgs = [], []
for i, user_id in enumerate(user_order):
    test_item = gt_lookup.get(user_id)
    if test_item is None:
        continue

    seen = user_items.get(user_id, set())
    candidates = all_item_ids[~np.isin(all_item_ids, list(seen))]
    neg_sample = rng.choice(candidates, size=min(N_NEGATIVES, len(candidates)), replace=False)

    candidate_ids = [test_item] + list(neg_sample)
    candidate_idxs = [item_name_to_idx[c] for c in candidate_ids if c in item_name_to_idx]
    candidate_scores = all_scores[i, candidate_idxs]

    test_score = all_scores[i, item_name_to_idx[test_item]]
    rank = int((candidate_scores > test_score).sum()) + 1

    if rank <= TOP_K:
        hits.append(1)
        ndcgs.append(1.0 / np.log2(rank + 1))
    else:
        hits.append(0)
        ndcgs.append(0.0)

print(f"\n{'=' * 40}")
print(f"Evaluation: 1 positive + {N_NEGATIVES} random negatives")
print(f"HR@{TOP_K}   : {np.mean(hits):.4f}")
print(f"NDCG@{TOP_K} : {np.mean(ndcgs):.4f}")
print(f"Users evaluated: {len(hits):,}")
print(f"{'=' * 40}")

Evaluating 6,040 users (sampled ranking: 1 positive + 100 negatives)...

2026-04-29 01:28:05,938 - skrec.recommender.sequential.sequential_recommender - INFO Built sequences for 6040 users (max_len=200, has_outcome=True).

2026-04-29 01:28:05,938 skrec.recommender.sequential.sequential_recommender INFO Built sequences for 6040 users (max_len=200, has_outcome=True).

========================================
Evaluation: 1 positive + 100 random negatives
HR@10   : 0.8568
NDCG@10 : 0.5795
Users evaluated: 6,040
========================================

## 9. Breakdown: HR@10 by Test Item Rating

Since the test item has a known rating, we can check whether the model is
better at predicting items the user *liked* versus items they *disliked*.
A well-trained model should show higher HR@10 for 4–5 star test items because
those items are more similar to the items already in the user's high-rated sequence.

In [10]:
gt_rating_lookup = eval_test_df.set_index("USER_ID")["OUTCOME"].to_dict()

records = []
for i, user_id in enumerate(user_order):
    test_item = gt_lookup.get(user_id)
    test_rating = gt_rating_lookup.get(user_id)
    if test_item is None:
        continue
    seen = user_items.get(user_id, set())
    candidates = all_item_ids[~np.isin(all_item_ids, list(seen))]
    neg_sample = rng.choice(candidates, size=min(N_NEGATIVES, len(candidates)), replace=False)
    candidate_ids = [test_item] + list(neg_sample)
    candidate_idxs = [item_name_to_idx[c] for c in candidate_ids if c in item_name_to_idx]
    candidate_scores = all_scores[i, candidate_idxs]
    test_score = all_scores[i, item_name_to_idx[test_item]]
    rank = int((candidate_scores > test_score).sum()) + 1
    hit = int(rank <= TOP_K)
    ndcg = (1.0 / np.log2(rank + 1)) if hit else 0.0
    records.append({"test_rating": int(test_rating), "hit": hit, "ndcg": ndcg})

breakdown = (
    pd.DataFrame(records)
    .groupby("test_rating")
    .agg(
        n_users=("hit", "count"),
        HR10=("hit", "mean"),
        NDCG10=("ndcg", "mean"),
    )
    .round(4)
)

print("HR@10 and NDCG@10 broken down by test item rating (sampled eval):")
print(breakdown.to_string())

HR@10 and NDCG@10 broken down by test item rating (sampled eval):
             n_users    HR10  NDCG10
test_rating
0               4467  0.8413  0.5512
1               1573  0.9072  0.6597

## 10. Sample Recommendations

Show top-10 recommendations for a few users alongside their held-out test item
and its rating.

In [11]:
movie_title = movies.set_index(movies["MovieID"].astype(str))["Title"].to_dict()
gt_rating_lookup = eval_test_df.set_index("USER_ID")["OUTCOME"].to_dict()

# Use all-except-test history (same as evaluation) so sequences are consistent
top_k_recs = recommender.recommend(interactions=eval_history_df, top_k=TOP_K)

for user_id in user_order[:5]:
    idx = user_order.index(user_id)
    recs = list(top_k_recs[idx])
    test_item = gt_lookup.get(user_id, "?")
    test_rating = gt_rating_lookup.get(user_id, "?")
    hit = "HIT" if test_item in recs else "MISS"
    print(
        f"\nUser {user_id}  |  Test item: {movie_title.get(test_item, test_item)} (rated {test_rating:.0f}/5)  [{hit}]"
    )
    print("  Top-10 (full-item ranking):")
    for rank, item_id in enumerate(recs, 1):
        marker = " <-- TEST ITEM" if item_id == test_item else ""
        print(f"    {rank:2}. {movie_title.get(item_id, item_id)}{marker}")

2026-04-29 01:28:09,973 - skrec.recommender.sequential.sequential_recommender - INFO Built sequences for 6040 users (max_len=200, has_outcome=True).

2026-04-29 01:28:09,973 skrec.recommender.sequential.sequential_recommender INFO Built sequences for 6040 users (max_len=200, has_outcome=True).

User 1  |  Test item: Pocahontas (1995) (rated 1/5)  [MISS]
  Top-10 (full-item ranking):
     1. Mulan (1998)
     2. Secret Garden, The (1993)
     3. Lion King, The (1994)
     4. Fantasia 2000 (1999)
     5. Anastasia (1997)
     6. Little Princess, A (1995)
     7. Toy Story (1995)
     8. Aladdin (1992)
     9. Muppet Christmas Carol, The (1992)
    10. Prince of Egypt, The (1998)

User 10  |  Test item: Hero (1992) (rated 1/5)  [MISS]
  Top-10 (full-item ranking):
     1. It's a Wonderful Life (1946)
     2. To Kill a Mockingbird (1962)
     3. Rear Window (1954)
     4. Schindler's List (1993)
     5. Sixth Sense, The (1999)
     6. Seven Samurai (The Magnificent Seven) (Shichinin no samurai) (1954)
     7. Vertigo (1958)
     8. Bridge on the River Kwai, The (1957)
     9. Midnight Cowboy (1969)
    10. Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1963)

User 100  |  Test item: Apocalypse Now (1979) (rated 0/5)  [MISS]
  Top-10 (full-item ranking):
     1. Good Will Hunting (1997)
     2. Life Is Beautiful (La Vita è bella) (1997)
     3. Shawshank Redemption, The (1994)
     4. October Sky (1999)
     5. Schindler's List (1993)
     6. Saving Private Ryan (1998)
     7. Sling Blade (1996)
     8. Sixth Sense, The (1999)
     9. Some Folks Call It a Sling Blade (1993)
    10. GoodFellas (1990)

User 1000  |  Test item: Streetcar Named Desire, A (1951) (rated 1/5)  [MISS]
  Top-10 (full-item ranking):
     1. It's a Wonderful Life (1946)
     2. Schindler's List (1993)
     3. Good Will Hunting (1997)
     4. Shawshank Redemption, The (1994)
     5. Glory (1989)
     6. Patton (1970)
     7. Breaking Away (1979)
     8. Life Is Beautiful (La Vita è bella) (1997)
     9. Right Stuff, The (1983)
    10. To Kill a Mockingbird (1962)

User 1001  |  Test item: Austin Powers: The Spy Who Shagged Me (1999) (rated 0/5)  [MISS]
  Top-10 (full-item ranking):
     1. Golden Bowl, The (2000)
     2. Following (1998)
     3. Urbania (2000)
     4. Yards, The (1999)
     5. Two Family House (2000)
     6. Affair of Love, An (Une Liaison Pornographique) (1999)
     7. Requiem for a Dream (2000)
     8. Girlfight (2000)
     9. Big Combo, The (1955)
    10. Dancer in the Dark (2000)