# SASRec on MovieLens 1M — Full Rating Signal (1–5)

This notebook is a companion to `sasrec_movielens1m_positives.ipynb` and demonstrates
**full-signal** training using normalized 1–5 ratings as soft BCE labels.

## Key differences from the positives-only notebook

| | Positives-only (notebook 1) | Full-signal (this notebook) |
|---|---|---|
| Interactions used | Rating ≥ 4 only | All 1–5 ratings |
| OUTCOME | 1.0 (binary) | Rating/5 (0.2–1.0, soft label) |
| Estimator | `SASRecClassifierEstimator` (BCE) | `SASRecClassifierEstimator` (BCE, soft labels) |
| Random negatives | target = 0.0 | target = 0.0 (below any real interaction) |

## How soft-label BCE works

Instead of MSE on raw 1–5 ratings, we normalise to [0.2, 1.0] by dividing by 5.  
BCEWithLogitsLoss with soft targets [0, 1] pushes each item's score toward a value
whose sigmoid equals the normalised rating:

- Rating 5 → target 1.0 → score pushed high (most liked)
- Rating 1 → target 0.2 → score pushed slightly positive
- Random negative → target 0.0 → score pushed negative

This means **all interacted items score above all non-interacted items**, regardless of
rating, which directly optimises the HR@10 evaluation metric.  High-rated items also
score higher than low-rated ones, preserving the preference gradient.

## 1. Imports

In [1]:
import logging
import urllib.request
import zipfile
from pathlib import Path

import numpy as np
import pandas as pd

from skrec.dataset.interactions_dataset import InteractionsDataset
from skrec.dataset.items_dataset import ItemsDataset
from skrec.estimator.sequential import SASRecClassifierEstimator
from skrec.recommender.sequential import SequentialRecommender
from skrec.scorer.sequential import SequentialScorer

# Show training loss logs from the estimator
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(name)s %(levelname)s %(message)s")

RAW_DIR = Path("data/movielens-1m")
RAW_DIR.mkdir(parents=True, exist_ok=True)
DATA_DIR = Path("data/sasrec-ratings")
DATA_DIR.mkdir(parents=True, exist_ok=True)
print("Imports OK")

Imports OK

## 2. Download MovieLens 1M

Data is stored in `examples/data/ml-1m/` (excluded from git via `.gitignore`).  
If the files already exist from running notebook 1, this step is a no-op.

In [2]:
ML1M_URL = "https://files.grouplens.org/datasets/movielens/ml-1m.zip"
zip_path = RAW_DIR / "ml-1m.zip"

if not (RAW_DIR / "ratings.dat").exists():
    print("Downloading MovieLens 1M...")
    urllib.request.urlretrieve(ML1M_URL, zip_path)
    with zipfile.ZipFile(zip_path) as zf:
        for name in zf.namelist():
            if name.endswith(".dat"):
                filename = Path(name).name
                with zf.open(name) as src, open(RAW_DIR / filename, "wb") as dst:
                    dst.write(src.read())
    print("Downloaded and extracted.")
else:
    print("Already downloaded.")

Already downloaded.

## 3. Load and Preprocess — All Ratings as Soft Labels

Unlike the positives-only notebook, we keep **all 1M interactions**.  
OUTCOME is normalised to [0.2, 1.0] by dividing the raw rating by 5, so every real
interaction has a target **strictly above** the random-negative target of 0.0.  
Higher-rated items simply receive a stronger positive gradient.

In [3]:
# ratings.dat: UserID::MovieID::Rating::Timestamp
ratings = pd.read_csv(
    RAW_DIR / "ratings.dat",
    sep="::",
    engine="python",
    names=["UserID", "MovieID", "Rating", "Timestamp"],
)

# movies.dat: MovieID::Title::Genres
movies = pd.read_csv(
    RAW_DIR / "movies.dat",
    sep="::",
    engine="python",
    names=["MovieID", "Title", "Genres"],
    encoding="latin-1",
)

print(f"Ratings: {len(ratings):,}  |  Users: {ratings.UserID.nunique():,}  |  Movies: {ratings.MovieID.nunique():,}")
ratings.head()

Ratings: 1,000,209  |  Users: 6,040  |  Movies: 3,706

   UserID  MovieID  Rating  Timestamp
0       1     1193       5  978300760
1       1      661       3  978302109
2       1      914       3  978301968
3       1     3408       4  978300275
4       1     2355       5  978824291

In [4]:
# Map to library column names.
# OUTCOME: normalised rating (1.0–5.0) / 5 → soft label [0.2, 1.0].
# Random negatives sampled at training time will receive target=0.0,
# which is 1 unit below the worst real rating (1.0), giving the model a
# clear learned boundary: unseen < hated < ... < loved.
interactions = pd.DataFrame(
    {
        "USER_ID": ratings["UserID"].astype(str),
        "ITEM_ID": ratings["MovieID"].astype(str),
        "OUTCOME": ratings["Rating"].astype(float) / 5.0,  # 0.2, 0.4, 0.6, 0.8, or 1.0
        # Keep TIMESTAMP as int64 (not str) so sort is numeric, not lexicographic.
        # ML-1M timestamps span 9- and 10-digit values; string sort would order them wrong.
        "TIMESTAMP": ratings["Timestamp"],
    }
)

items = pd.DataFrame({"ITEM_ID": movies["MovieID"].astype(str)})

print(f"Total interactions: {len(interactions):,}")
interactions.head()

Total interactions: 1,000,209

  USER_ID ITEM_ID  OUTCOME  TIMESTAMP
0       1    1193      1.0  978300760
1       1     661      0.6  978302109
2       1     914      0.6  978301968
3       1    3408      0.8  978300275
4       1    2355      1.0  978824291

## 4. Rating Distribution

Unlike the positives-only notebook, our training sequences now contain the full
distribution of ratings. This section gives a feel for what the model will learn from.

In [5]:
rating_counts = ratings["Rating"].value_counts().sort_index()
print("Rating distribution (all interactions):")
print("=" * 40)
for rating, count in rating_counts.items():
    bar = "#" * (count // 10000)
    print(f"  {rating} stars: {count:>7,}  ({count / len(ratings):.1%})  {bar}")
print("=" * 40)
print(f"  Mean rating : {ratings['Rating'].mean():.2f}")
print(f"  Median      : {ratings['Rating'].median():.1f}")

Rating distribution (all interactions):
========================================
  1 stars:  56,174  (5.6%)  #####
  2 stars: 107,557  (10.8%)  ##########
  3 stars: 261,197  (26.1%)  ##########################
  4 stars: 348,971  (34.9%)  ##################################
  5 stars: 226,310  (22.6%)  ######################
========================================
  Mean rating : 3.58
  Median      : 4.0

## 5. Train / Test Split (Leave-Last-Out on All Interactions)

For each user, the interaction with the largest timestamp is the test item —
regardless of its rating. This is a stricter protocol than the positives-only
notebook: the model must predict the user's *next actual behavior*, not just
their next liked item.

Users with fewer than 5 total interactions are excluded.

In [6]:
# Sort by timestamp
interactions = interactions.sort_values(["USER_ID", "TIMESTAMP"]).reset_index(drop=True)

# Keep users with >= 5 interactions
user_counts = interactions.groupby("USER_ID").size()
valid_users = user_counts[user_counts >= 5].index
interactions = interactions[interactions["USER_ID"].isin(valid_users)].reset_index(drop=True)

# Rank items per user (0 = most recent = test)
interactions["rank"] = interactions.groupby("USER_ID").cumcount(ascending=False)
test_df = interactions[interactions["rank"] == 0].drop(columns=["rank"]).reset_index(drop=True)
valid_df = interactions[interactions["rank"] == 1].drop(columns=["rank"]).reset_index(drop=True)

# Training uses ALL interactions (matches original SASRec paper).
# The test item is used as the last training target: the model trains to predict it
# from the preceding history, which is exactly the task being evaluated.
train_df = interactions.drop(columns=["rank"]).reset_index(drop=True)

# Evaluation history: all interactions EXCEPT the test item.
all_except_test_df = interactions[interactions["rank"] >= 1].drop(columns=["rank"]).reset_index(drop=True)

print(f"Train interactions : {len(train_df):,}  (ALL interactions — test item used as last target)")
print(f"Valid interactions : {len(valid_df):,}  (one per user, for reference)")
print(f"Test  interactions : {len(test_df):,}  (one per user)")
print(f"Users              : {train_df.USER_ID.nunique():,}")
print()
print("Rating distribution of held-out test items:")
print(test_df["OUTCOME"].value_counts().sort_index().to_string())

Train interactions : 1,000,209  (ALL interactions — test item used as last target)
Valid interactions : 6,040  (one per user, for reference)
Test  interactions : 6,040  (one per user)
Users              : 6,040

Rating distribution of held-out test items:
OUTCOME
0.2     407
0.4     657
0.6    1413
0.8    1990
1.0    1573

## 6. Save CSVs and Create Datasets

In [7]:
train_path = str(DATA_DIR / "train_interactions.csv")
items_path = str(DATA_DIR / "items.csv")

# Train on ALL interactions (reference SASRec: test item is last training target per user)
if not Path(train_path).exists():
    train_df.to_csv(train_path, index=False)
if not Path(items_path).exists():
    items.to_csv(items_path, index=False)

interactions_ds = InteractionsDataset(data_location=train_path)
items_ds = ItemsDataset(data_location=items_path)

print(f"Training data: {len(train_df):,} interactions")
print("Datasets created.")

Training data: 1,000,209 interactions
Datasets created.

## 7. Build and Train SASRec (Classifier with Soft Labels)

We use `SASRecClassifierEstimator` (BCE) with soft labels and `num_negatives=1`.

**Why soft-label BCE?**  
BCEWithLogitsLoss natively supports targets in [0, 1].  Normalising ratings to
Rating/5 gives a graduated signal while keeping the loss bounded and well-conditioned.  
The model converges faster and learns more discriminative item embeddings than MSE on
raw 1–5 targets.

**Why `num_negatives=1`?**  
At each training step, one random unseen item is sampled with `target=0.0`.
Since the minimum normalised rating is 0.2, this creates a 0.2-unit gap that pushes
unseen items below even disliked ones — the core of the full-signal approach.

In [8]:
estimator = SASRecClassifierEstimator(
    hidden_units=50,
    num_blocks=2,
    num_heads=1,
    dropout_rate=0.2,
    num_negatives=1,  # original paper: 1 negative per step
    learning_rate=0.001,
    epochs=200,
    batch_size=128,
    optimizer_name="adam",
    loss_fn_name="bce",
    verbose=1,
)

scorer = SequentialScorer(estimator)
recommender = SequentialRecommender(scorer, max_len=200)

print("Training SASRec (soft-label BCE)...")
recommender.train(items_ds=items_ds, interactions_ds=interactions_ds)
print("Training complete.")

Training SASRec (soft-label BCE)...

2026-04-17 10:46:50,278 - skrec.recommender.sequential.sequential_recommender - WARNING SequentialRecommender.max_len=200 overrides SASRecClassifierEstimator.max_len=50. Pass the same max_len to both, or rely on the recommender's value.

2026-04-17 10:46:50,278 skrec.recommender.sequential.sequential_recommender WARNING SequentialRecommender.max_len=200 overrides SASRecClassifierEstimator.max_len=50. Pass the same max_len to both, or rely on the recommender's value.

2026-04-17 10:46:50,546 - skrec.recommender.sequential.sequential_recommender - INFO Built sequences for 6040 users (max_len=200, has_outcome=True).

2026-04-17 10:46:50,546 skrec.recommender.sequential.sequential_recommender INFO Built sequences for 6040 users (max_len=200, has_outcome=True).

2026-04-17 10:46:57,573 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [1/200], Loss: 1.1881

2026-04-17 10:46:57,573 skrec.estimator.sequential.sasrec_estimator INFO Epoch [1/200], Loss: 1.1881

2026-04-17 10:47:03,788 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [2/200], Loss: 1.0476

2026-04-17 10:47:03,788 skrec.estimator.sequential.sasrec_estimator INFO Epoch [2/200], Loss: 1.0476

2026-04-17 10:47:10,026 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [3/200], Loss: 1.0226

2026-04-17 10:47:10,026 skrec.estimator.sequential.sasrec_estimator INFO Epoch [3/200], Loss: 1.0226

2026-04-17 10:47:16,231 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [4/200], Loss: 1.0022

2026-04-17 10:47:16,231 skrec.estimator.sequential.sasrec_estimator INFO Epoch [4/200], Loss: 1.0022

2026-04-17 10:47:22,473 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [5/200], Loss: 0.9806

2026-04-17 10:47:22,473 skrec.estimator.sequential.sasrec_estimator INFO Epoch [5/200], Loss: 0.9806

2026-04-17 10:47:28,690 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [6/200], Loss: 0.9604

2026-04-17 10:47:28,690 skrec.estimator.sequential.sasrec_estimator INFO Epoch [6/200], Loss: 0.9604

2026-04-17 10:47:34,888 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [7/200], Loss: 0.9461

2026-04-17 10:47:34,888 skrec.estimator.sequential.sasrec_estimator INFO Epoch [7/200], Loss: 0.9461

2026-04-17 10:47:41,598 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [8/200], Loss: 0.9337

2026-04-17 10:47:41,598 skrec.estimator.sequential.sasrec_estimator INFO Epoch [8/200], Loss: 0.9337

2026-04-17 10:47:48,024 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [9/200], Loss: 0.9229

2026-04-17 10:47:48,024 skrec.estimator.sequential.sasrec_estimator INFO Epoch [9/200], Loss: 0.9229

2026-04-17 10:47:54,819 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [10/200], Loss: 0.9113

2026-04-17 10:47:54,819 skrec.estimator.sequential.sasrec_estimator INFO Epoch [10/200], Loss: 0.9113

2026-04-17 10:48:01,198 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [11/200], Loss: 0.9002

2026-04-17 10:48:01,198 skrec.estimator.sequential.sasrec_estimator INFO Epoch [11/200], Loss: 0.9002

2026-04-17 10:48:07,794 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [12/200], Loss: 0.8923

2026-04-17 10:48:07,794 skrec.estimator.sequential.sasrec_estimator INFO Epoch [12/200], Loss: 0.8923

2026-04-17 10:48:14,349 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [13/200], Loss: 0.8850

2026-04-17 10:48:14,349 skrec.estimator.sequential.sasrec_estimator INFO Epoch [13/200], Loss: 0.8850

2026-04-17 10:48:20,813 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [14/200], Loss: 0.8799

2026-04-17 10:48:20,813 skrec.estimator.sequential.sasrec_estimator INFO Epoch [14/200], Loss: 0.8799

2026-04-17 10:48:27,341 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [15/200], Loss: 0.8753

2026-04-17 10:48:27,341 skrec.estimator.sequential.sasrec_estimator INFO Epoch [15/200], Loss: 0.8753

2026-04-17 10:48:33,917 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [16/200], Loss: 0.8693

2026-04-17 10:48:33,917 skrec.estimator.sequential.sasrec_estimator INFO Epoch [16/200], Loss: 0.8693

2026-04-17 10:48:40,304 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [17/200], Loss: 0.8650

2026-04-17 10:48:40,304 skrec.estimator.sequential.sasrec_estimator INFO Epoch [17/200], Loss: 0.8650

2026-04-17 10:48:46,778 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [18/200], Loss: 0.8611

2026-04-17 10:48:46,778 skrec.estimator.sequential.sasrec_estimator INFO Epoch [18/200], Loss: 0.8611

2026-04-17 10:48:53,159 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [19/200], Loss: 0.8580

2026-04-17 10:48:53,159 skrec.estimator.sequential.sasrec_estimator INFO Epoch [19/200], Loss: 0.8580

2026-04-17 10:48:59,480 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [20/200], Loss: 0.8534

2026-04-17 10:48:59,480 skrec.estimator.sequential.sasrec_estimator INFO Epoch [20/200], Loss: 0.8534

2026-04-17 10:49:05,784 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [21/200], Loss: 0.8494

2026-04-17 10:49:05,784 skrec.estimator.sequential.sasrec_estimator INFO Epoch [21/200], Loss: 0.8494

2026-04-17 10:49:12,124 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [22/200], Loss: 0.8468

2026-04-17 10:49:12,124 skrec.estimator.sequential.sasrec_estimator INFO Epoch [22/200], Loss: 0.8468

2026-04-17 10:49:18,569 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [23/200], Loss: 0.8435

2026-04-17 10:49:18,569 skrec.estimator.sequential.sasrec_estimator INFO Epoch [23/200], Loss: 0.8435

2026-04-17 10:49:24,880 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [24/200], Loss: 0.8405

2026-04-17 10:49:24,880 skrec.estimator.sequential.sasrec_estimator INFO Epoch [24/200], Loss: 0.8405

2026-04-17 10:49:31,176 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [25/200], Loss: 0.8381

2026-04-17 10:49:31,176 skrec.estimator.sequential.sasrec_estimator INFO Epoch [25/200], Loss: 0.8381

2026-04-17 10:49:37,561 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [26/200], Loss: 0.8365

2026-04-17 10:49:37,561 skrec.estimator.sequential.sasrec_estimator INFO Epoch [26/200], Loss: 0.8365

2026-04-17 10:49:43,995 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [27/200], Loss: 0.8344

2026-04-17 10:49:43,995 skrec.estimator.sequential.sasrec_estimator INFO Epoch [27/200], Loss: 0.8344

2026-04-17 10:49:50,402 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [28/200], Loss: 0.8316

2026-04-17 10:49:50,402 skrec.estimator.sequential.sasrec_estimator INFO Epoch [28/200], Loss: 0.8316

2026-04-17 10:49:56,908 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [29/200], Loss: 0.8292

2026-04-17 10:49:56,908 skrec.estimator.sequential.sasrec_estimator INFO Epoch [29/200], Loss: 0.8292

2026-04-17 10:50:03,497 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [30/200], Loss: 0.8287

2026-04-17 10:50:03,497 skrec.estimator.sequential.sasrec_estimator INFO Epoch [30/200], Loss: 0.8287

2026-04-17 10:50:10,135 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [31/200], Loss: 0.8260

2026-04-17 10:50:10,135 skrec.estimator.sequential.sasrec_estimator INFO Epoch [31/200], Loss: 0.8260

2026-04-17 10:50:16,565 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [32/200], Loss: 0.8244

2026-04-17 10:50:16,565 skrec.estimator.sequential.sasrec_estimator INFO Epoch [32/200], Loss: 0.8244

2026-04-17 10:50:23,005 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [33/200], Loss: 0.8234

2026-04-17 10:50:23,005 skrec.estimator.sequential.sasrec_estimator INFO Epoch [33/200], Loss: 0.8234

2026-04-17 10:50:29,481 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [34/200], Loss: 0.8216

2026-04-17 10:50:29,481 skrec.estimator.sequential.sasrec_estimator INFO Epoch [34/200], Loss: 0.8216

2026-04-17 10:50:35,871 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [35/200], Loss: 0.8200

2026-04-17 10:50:35,871 skrec.estimator.sequential.sasrec_estimator INFO Epoch [35/200], Loss: 0.8200

2026-04-17 10:50:42,393 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [36/200], Loss: 0.8185

2026-04-17 10:50:42,393 skrec.estimator.sequential.sasrec_estimator INFO Epoch [36/200], Loss: 0.8185

2026-04-17 10:50:48,866 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [37/200], Loss: 0.8180

2026-04-17 10:50:48,866 skrec.estimator.sequential.sasrec_estimator INFO Epoch [37/200], Loss: 0.8180

2026-04-17 10:50:55,377 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [38/200], Loss: 0.8164

2026-04-17 10:50:55,377 skrec.estimator.sequential.sasrec_estimator INFO Epoch [38/200], Loss: 0.8164

2026-04-17 10:51:01,719 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [39/200], Loss: 0.8158

2026-04-17 10:51:01,719 skrec.estimator.sequential.sasrec_estimator INFO Epoch [39/200], Loss: 0.8158

2026-04-17 10:51:08,064 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [40/200], Loss: 0.8151

2026-04-17 10:51:08,064 skrec.estimator.sequential.sasrec_estimator INFO Epoch [40/200], Loss: 0.8151

2026-04-17 10:51:14,483 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [41/200], Loss: 0.8130

2026-04-17 10:51:14,483 skrec.estimator.sequential.sasrec_estimator INFO Epoch [41/200], Loss: 0.8130

2026-04-17 10:51:21,231 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [42/200], Loss: 0.8126

2026-04-17 10:51:21,231 skrec.estimator.sequential.sasrec_estimator INFO Epoch [42/200], Loss: 0.8126

2026-04-17 10:51:27,722 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [43/200], Loss: 0.8105

2026-04-17 10:51:27,722 skrec.estimator.sequential.sasrec_estimator INFO Epoch [43/200], Loss: 0.8105

2026-04-17 10:51:34,134 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [44/200], Loss: 0.8093

2026-04-17 10:51:34,134 skrec.estimator.sequential.sasrec_estimator INFO Epoch [44/200], Loss: 0.8093

2026-04-17 10:51:40,616 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [45/200], Loss: 0.8093

2026-04-17 10:51:40,616 skrec.estimator.sequential.sasrec_estimator INFO Epoch [45/200], Loss: 0.8093

2026-04-17 10:51:47,371 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [46/200], Loss: 0.8091

2026-04-17 10:51:47,371 skrec.estimator.sequential.sasrec_estimator INFO Epoch [46/200], Loss: 0.8091

2026-04-17 10:51:53,974 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [47/200], Loss: 0.8078

2026-04-17 10:51:53,974 skrec.estimator.sequential.sasrec_estimator INFO Epoch [47/200], Loss: 0.8078

2026-04-17 10:52:00,337 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [48/200], Loss: 0.8067

2026-04-17 10:52:00,337 skrec.estimator.sequential.sasrec_estimator INFO Epoch [48/200], Loss: 0.8067

2026-04-17 10:52:06,664 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [49/200], Loss: 0.8067

2026-04-17 10:52:06,664 skrec.estimator.sequential.sasrec_estimator INFO Epoch [49/200], Loss: 0.8067

2026-04-17 10:52:13,046 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [50/200], Loss: 0.8059

2026-04-17 10:52:13,046 skrec.estimator.sequential.sasrec_estimator INFO Epoch [50/200], Loss: 0.8059

2026-04-17 10:52:19,412 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [51/200], Loss: 0.8039

2026-04-17 10:52:19,412 skrec.estimator.sequential.sasrec_estimator INFO Epoch [51/200], Loss: 0.8039

2026-04-17 10:52:25,772 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [52/200], Loss: 0.8040

2026-04-17 10:52:25,772 skrec.estimator.sequential.sasrec_estimator INFO Epoch [52/200], Loss: 0.8040

2026-04-17 10:52:32,100 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [53/200], Loss: 0.8024

2026-04-17 10:52:32,100 skrec.estimator.sequential.sasrec_estimator INFO Epoch [53/200], Loss: 0.8024

2026-04-17 10:52:38,631 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [54/200], Loss: 0.8034

2026-04-17 10:52:38,631 skrec.estimator.sequential.sasrec_estimator INFO Epoch [54/200], Loss: 0.8034

2026-04-17 10:52:44,975 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [55/200], Loss: 0.8020

2026-04-17 10:52:44,975 skrec.estimator.sequential.sasrec_estimator INFO Epoch [55/200], Loss: 0.8020

2026-04-17 10:52:51,305 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [56/200], Loss: 0.8014

2026-04-17 10:52:51,305 skrec.estimator.sequential.sasrec_estimator INFO Epoch [56/200], Loss: 0.8014

2026-04-17 10:52:57,747 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [57/200], Loss: 0.7998

2026-04-17 10:52:57,747 skrec.estimator.sequential.sasrec_estimator INFO Epoch [57/200], Loss: 0.7998

2026-04-17 10:53:04,498 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [58/200], Loss: 0.8006

2026-04-17 10:53:04,498 skrec.estimator.sequential.sasrec_estimator INFO Epoch [58/200], Loss: 0.8006

2026-04-17 10:53:10,945 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [59/200], Loss: 0.7987

2026-04-17 10:53:10,945 skrec.estimator.sequential.sasrec_estimator INFO Epoch [59/200], Loss: 0.7987

2026-04-17 10:53:17,275 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [60/200], Loss: 0.7989

2026-04-17 10:53:17,275 skrec.estimator.sequential.sasrec_estimator INFO Epoch [60/200], Loss: 0.7989

2026-04-17 10:53:23,657 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [61/200], Loss: 0.7975

2026-04-17 10:53:23,657 skrec.estimator.sequential.sasrec_estimator INFO Epoch [61/200], Loss: 0.7975

2026-04-17 10:53:30,023 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [62/200], Loss: 0.7982

2026-04-17 10:53:30,023 skrec.estimator.sequential.sasrec_estimator INFO Epoch [62/200], Loss: 0.7982

2026-04-17 10:53:36,374 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [63/200], Loss: 0.7973

2026-04-17 10:53:36,374 skrec.estimator.sequential.sasrec_estimator INFO Epoch [63/200], Loss: 0.7973

2026-04-17 10:53:42,748 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [64/200], Loss: 0.7970

2026-04-17 10:53:42,748 skrec.estimator.sequential.sasrec_estimator INFO Epoch [64/200], Loss: 0.7970

2026-04-17 10:53:49,060 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [65/200], Loss: 0.7956

2026-04-17 10:53:49,060 skrec.estimator.sequential.sasrec_estimator INFO Epoch [65/200], Loss: 0.7956

2026-04-17 10:53:55,370 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [66/200], Loss: 0.7959

2026-04-17 10:53:55,370 skrec.estimator.sequential.sasrec_estimator INFO Epoch [66/200], Loss: 0.7959

2026-04-17 10:54:02,472 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [67/200], Loss: 0.7955

2026-04-17 10:54:02,472 skrec.estimator.sequential.sasrec_estimator INFO Epoch [67/200], Loss: 0.7955

2026-04-17 10:54:09,392 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [68/200], Loss: 0.7956

2026-04-17 10:54:09,392 skrec.estimator.sequential.sasrec_estimator INFO Epoch [68/200], Loss: 0.7956

2026-04-17 10:54:16,165 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [69/200], Loss: 0.7942

2026-04-17 10:54:16,165 skrec.estimator.sequential.sasrec_estimator INFO Epoch [69/200], Loss: 0.7942

2026-04-17 10:54:22,808 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [70/200], Loss: 0.7940

2026-04-17 10:54:22,808 skrec.estimator.sequential.sasrec_estimator INFO Epoch [70/200], Loss: 0.7940

2026-04-17 10:54:29,313 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [71/200], Loss: 0.7932

2026-04-17 10:54:29,313 skrec.estimator.sequential.sasrec_estimator INFO Epoch [71/200], Loss: 0.7932

2026-04-17 10:54:35,771 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [72/200], Loss: 0.7925

2026-04-17 10:54:35,771 skrec.estimator.sequential.sasrec_estimator INFO Epoch [72/200], Loss: 0.7925

2026-04-17 10:54:42,280 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [73/200], Loss: 0.7921

2026-04-17 10:54:42,280 skrec.estimator.sequential.sasrec_estimator INFO Epoch [73/200], Loss: 0.7921

2026-04-17 10:54:48,727 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [74/200], Loss: 0.7922

2026-04-17 10:54:48,727 skrec.estimator.sequential.sasrec_estimator INFO Epoch [74/200], Loss: 0.7922

2026-04-17 10:54:55,074 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [75/200], Loss: 0.7910

2026-04-17 10:54:55,074 skrec.estimator.sequential.sasrec_estimator INFO Epoch [75/200], Loss: 0.7910

2026-04-17 10:55:01,573 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [76/200], Loss: 0.7911

2026-04-17 10:55:01,573 skrec.estimator.sequential.sasrec_estimator INFO Epoch [76/200], Loss: 0.7911

2026-04-17 10:55:07,986 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [77/200], Loss: 0.7907

2026-04-17 10:55:07,986 skrec.estimator.sequential.sasrec_estimator INFO Epoch [77/200], Loss: 0.7907

2026-04-17 10:55:14,400 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [78/200], Loss: 0.7895

2026-04-17 10:55:14,400 skrec.estimator.sequential.sasrec_estimator INFO Epoch [78/200], Loss: 0.7895

2026-04-17 10:55:20,819 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [79/200], Loss: 0.7891

2026-04-17 10:55:20,819 skrec.estimator.sequential.sasrec_estimator INFO Epoch [79/200], Loss: 0.7891

2026-04-17 10:55:27,195 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [80/200], Loss: 0.7899

2026-04-17 10:55:27,195 skrec.estimator.sequential.sasrec_estimator INFO Epoch [80/200], Loss: 0.7899

2026-04-17 10:55:33,667 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [81/200], Loss: 0.7896

2026-04-17 10:55:33,667 skrec.estimator.sequential.sasrec_estimator INFO Epoch [81/200], Loss: 0.7896

2026-04-17 10:55:40,104 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [82/200], Loss: 0.7885

2026-04-17 10:55:40,104 skrec.estimator.sequential.sasrec_estimator INFO Epoch [82/200], Loss: 0.7885

2026-04-17 10:55:46,512 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [83/200], Loss: 0.7877

2026-04-17 10:55:46,512 skrec.estimator.sequential.sasrec_estimator INFO Epoch [83/200], Loss: 0.7877

2026-04-17 10:55:52,909 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [84/200], Loss: 0.7890

2026-04-17 10:55:52,909 skrec.estimator.sequential.sasrec_estimator INFO Epoch [84/200], Loss: 0.7890

2026-04-17 10:55:59,325 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [85/200], Loss: 0.7877

2026-04-17 10:55:59,325 skrec.estimator.sequential.sasrec_estimator INFO Epoch [85/200], Loss: 0.7877

2026-04-17 10:56:05,781 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [86/200], Loss: 0.7883

2026-04-17 10:56:05,781 skrec.estimator.sequential.sasrec_estimator INFO Epoch [86/200], Loss: 0.7883

2026-04-17 10:56:12,159 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [87/200], Loss: 0.7870

2026-04-17 10:56:12,159 skrec.estimator.sequential.sasrec_estimator INFO Epoch [87/200], Loss: 0.7870

2026-04-17 10:56:18,542 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [88/200], Loss: 0.7877

2026-04-17 10:56:18,542 skrec.estimator.sequential.sasrec_estimator INFO Epoch [88/200], Loss: 0.7877

2026-04-17 10:56:24,934 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [89/200], Loss: 0.7874

2026-04-17 10:56:24,934 skrec.estimator.sequential.sasrec_estimator INFO Epoch [89/200], Loss: 0.7874

2026-04-17 10:56:31,321 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [90/200], Loss: 0.7859

2026-04-17 10:56:31,321 skrec.estimator.sequential.sasrec_estimator INFO Epoch [90/200], Loss: 0.7859

2026-04-17 10:56:37,785 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [91/200], Loss: 0.7861

2026-04-17 10:56:37,785 skrec.estimator.sequential.sasrec_estimator INFO Epoch [91/200], Loss: 0.7861

2026-04-17 10:56:44,240 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [92/200], Loss: 0.7854

2026-04-17 10:56:44,240 skrec.estimator.sequential.sasrec_estimator INFO Epoch [92/200], Loss: 0.7854

2026-04-17 10:56:50,640 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [93/200], Loss: 0.7856

2026-04-17 10:56:50,640 skrec.estimator.sequential.sasrec_estimator INFO Epoch [93/200], Loss: 0.7856

2026-04-17 10:56:57,061 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [94/200], Loss: 0.7854

2026-04-17 10:56:57,061 skrec.estimator.sequential.sasrec_estimator INFO Epoch [94/200], Loss: 0.7854

2026-04-17 10:57:03,481 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [95/200], Loss: 0.7841

2026-04-17 10:57:03,481 skrec.estimator.sequential.sasrec_estimator INFO Epoch [95/200], Loss: 0.7841

2026-04-17 10:57:10,070 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [96/200], Loss: 0.7839

2026-04-17 10:57:10,070 skrec.estimator.sequential.sasrec_estimator INFO Epoch [96/200], Loss: 0.7839

2026-04-17 10:57:16,619 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [97/200], Loss: 0.7841

2026-04-17 10:57:16,619 skrec.estimator.sequential.sasrec_estimator INFO Epoch [97/200], Loss: 0.7841

2026-04-17 10:57:23,027 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [98/200], Loss: 0.7854

2026-04-17 10:57:23,027 skrec.estimator.sequential.sasrec_estimator INFO Epoch [98/200], Loss: 0.7854

2026-04-17 10:57:29,385 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [99/200], Loss: 0.7837

2026-04-17 10:57:29,385 skrec.estimator.sequential.sasrec_estimator INFO Epoch [99/200], Loss: 0.7837

2026-04-17 10:57:35,740 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [100/200], Loss: 0.7838

2026-04-17 10:57:35,740 skrec.estimator.sequential.sasrec_estimator INFO Epoch [100/200], Loss: 0.7838

2026-04-17 10:57:42,109 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [101/200], Loss: 0.7834

2026-04-17 10:57:42,109 skrec.estimator.sequential.sasrec_estimator INFO Epoch [101/200], Loss: 0.7834

2026-04-17 10:57:48,537 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [102/200], Loss: 0.7833

2026-04-17 10:57:48,537 skrec.estimator.sequential.sasrec_estimator INFO Epoch [102/200], Loss: 0.7833

2026-04-17 10:57:54,929 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [103/200], Loss: 0.7836

2026-04-17 10:57:54,929 skrec.estimator.sequential.sasrec_estimator INFO Epoch [103/200], Loss: 0.7836

2026-04-17 10:58:01,439 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [104/200], Loss: 0.7825

2026-04-17 10:58:01,439 skrec.estimator.sequential.sasrec_estimator INFO Epoch [104/200], Loss: 0.7825

2026-04-17 10:58:07,962 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [105/200], Loss: 0.7818

2026-04-17 10:58:07,962 skrec.estimator.sequential.sasrec_estimator INFO Epoch [105/200], Loss: 0.7818

2026-04-17 10:58:14,692 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [106/200], Loss: 0.7833

2026-04-17 10:58:14,692 skrec.estimator.sequential.sasrec_estimator INFO Epoch [106/200], Loss: 0.7833

2026-04-17 10:58:21,278 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [107/200], Loss: 0.7812

2026-04-17 10:58:21,278 skrec.estimator.sequential.sasrec_estimator INFO Epoch [107/200], Loss: 0.7812

2026-04-17 10:58:27,696 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [108/200], Loss: 0.7820

2026-04-17 10:58:27,696 skrec.estimator.sequential.sasrec_estimator INFO Epoch [108/200], Loss: 0.7820

2026-04-17 10:58:34,243 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [109/200], Loss: 0.7807

2026-04-17 10:58:34,243 skrec.estimator.sequential.sasrec_estimator INFO Epoch [109/200], Loss: 0.7807

2026-04-17 10:58:40,835 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [110/200], Loss: 0.7821

2026-04-17 10:58:40,835 skrec.estimator.sequential.sasrec_estimator INFO Epoch [110/200], Loss: 0.7821

2026-04-17 10:58:47,441 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [111/200], Loss: 0.7811

2026-04-17 10:58:47,441 skrec.estimator.sequential.sasrec_estimator INFO Epoch [111/200], Loss: 0.7811

2026-04-17 10:58:53,932 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [112/200], Loss: 0.7811

2026-04-17 10:58:53,932 skrec.estimator.sequential.sasrec_estimator INFO Epoch [112/200], Loss: 0.7811

2026-04-17 10:59:00,446 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [113/200], Loss: 0.7806

2026-04-17 10:59:00,446 skrec.estimator.sequential.sasrec_estimator INFO Epoch [113/200], Loss: 0.7806

2026-04-17 10:59:06,981 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [114/200], Loss: 0.7810

2026-04-17 10:59:06,981 skrec.estimator.sequential.sasrec_estimator INFO Epoch [114/200], Loss: 0.7810

2026-04-17 10:59:13,485 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [115/200], Loss: 0.7811

2026-04-17 10:59:13,485 skrec.estimator.sequential.sasrec_estimator INFO Epoch [115/200], Loss: 0.7811

2026-04-17 10:59:20,050 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [116/200], Loss: 0.7798

2026-04-17 10:59:20,050 skrec.estimator.sequential.sasrec_estimator INFO Epoch [116/200], Loss: 0.7798

2026-04-17 10:59:26,638 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [117/200], Loss: 0.7798

2026-04-17 10:59:26,638 skrec.estimator.sequential.sasrec_estimator INFO Epoch [117/200], Loss: 0.7798

2026-04-17 10:59:33,238 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [118/200], Loss: 0.7802

2026-04-17 10:59:33,238 skrec.estimator.sequential.sasrec_estimator INFO Epoch [118/200], Loss: 0.7802

2026-04-17 10:59:39,796 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [119/200], Loss: 0.7800

2026-04-17 10:59:39,796 skrec.estimator.sequential.sasrec_estimator INFO Epoch [119/200], Loss: 0.7800

2026-04-17 10:59:46,254 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [120/200], Loss: 0.7793

2026-04-17 10:59:46,254 skrec.estimator.sequential.sasrec_estimator INFO Epoch [120/200], Loss: 0.7793

2026-04-17 10:59:52,676 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [121/200], Loss: 0.7794

2026-04-17 10:59:52,676 skrec.estimator.sequential.sasrec_estimator INFO Epoch [121/200], Loss: 0.7794

2026-04-17 10:59:59,110 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [122/200], Loss: 0.7781

2026-04-17 10:59:59,110 skrec.estimator.sequential.sasrec_estimator INFO Epoch [122/200], Loss: 0.7781

2026-04-17 11:00:05,495 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [123/200], Loss: 0.7793

2026-04-17 11:00:05,495 skrec.estimator.sequential.sasrec_estimator INFO Epoch [123/200], Loss: 0.7793

2026-04-17 11:00:11,900 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [124/200], Loss: 0.7783

2026-04-17 11:00:11,900 skrec.estimator.sequential.sasrec_estimator INFO Epoch [124/200], Loss: 0.7783

2026-04-17 11:00:18,450 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [125/200], Loss: 0.7783

2026-04-17 11:00:18,450 skrec.estimator.sequential.sasrec_estimator INFO Epoch [125/200], Loss: 0.7783

2026-04-17 11:00:24,872 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [126/200], Loss: 0.7784

2026-04-17 11:00:24,872 skrec.estimator.sequential.sasrec_estimator INFO Epoch [126/200], Loss: 0.7784

2026-04-17 11:00:31,253 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [127/200], Loss: 0.7788

2026-04-17 11:00:31,253 skrec.estimator.sequential.sasrec_estimator INFO Epoch [127/200], Loss: 0.7788

2026-04-17 11:00:37,715 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [128/200], Loss: 0.7787

2026-04-17 11:00:37,715 skrec.estimator.sequential.sasrec_estimator INFO Epoch [128/200], Loss: 0.7787

2026-04-17 11:00:44,139 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [129/200], Loss: 0.7784

2026-04-17 11:00:44,139 skrec.estimator.sequential.sasrec_estimator INFO Epoch [129/200], Loss: 0.7784

2026-04-17 11:00:50,658 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [130/200], Loss: 0.7777

2026-04-17 11:00:50,658 skrec.estimator.sequential.sasrec_estimator INFO Epoch [130/200], Loss: 0.7777

2026-04-17 11:00:57,189 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [131/200], Loss: 0.7782

2026-04-17 11:00:57,189 skrec.estimator.sequential.sasrec_estimator INFO Epoch [131/200], Loss: 0.7782

2026-04-17 11:01:03,594 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [132/200], Loss: 0.7768

2026-04-17 11:01:03,594 skrec.estimator.sequential.sasrec_estimator INFO Epoch [132/200], Loss: 0.7768

2026-04-17 11:01:09,950 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [133/200], Loss: 0.7768

2026-04-17 11:01:09,950 skrec.estimator.sequential.sasrec_estimator INFO Epoch [133/200], Loss: 0.7768

2026-04-17 11:01:16,362 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [134/200], Loss: 0.7764

2026-04-17 11:01:16,362 skrec.estimator.sequential.sasrec_estimator INFO Epoch [134/200], Loss: 0.7764

2026-04-17 11:01:22,861 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [135/200], Loss: 0.7776

2026-04-17 11:01:22,861 skrec.estimator.sequential.sasrec_estimator INFO Epoch [135/200], Loss: 0.7776

2026-04-17 11:01:29,271 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [136/200], Loss: 0.7766

2026-04-17 11:01:29,271 skrec.estimator.sequential.sasrec_estimator INFO Epoch [136/200], Loss: 0.7766

2026-04-17 11:01:35,673 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [137/200], Loss: 0.7760

2026-04-17 11:01:35,673 skrec.estimator.sequential.sasrec_estimator INFO Epoch [137/200], Loss: 0.7760

2026-04-17 11:01:42,169 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [138/200], Loss: 0.7765

2026-04-17 11:01:42,169 skrec.estimator.sequential.sasrec_estimator INFO Epoch [138/200], Loss: 0.7765

2026-04-17 11:01:48,746 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [139/200], Loss: 0.7758

2026-04-17 11:01:48,746 skrec.estimator.sequential.sasrec_estimator INFO Epoch [139/200], Loss: 0.7758

2026-04-17 11:01:55,292 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [140/200], Loss: 0.7763

2026-04-17 11:01:55,292 skrec.estimator.sequential.sasrec_estimator INFO Epoch [140/200], Loss: 0.7763

2026-04-17 11:02:01,757 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [141/200], Loss: 0.7767

2026-04-17 11:02:01,757 skrec.estimator.sequential.sasrec_estimator INFO Epoch [141/200], Loss: 0.7767

2026-04-17 11:02:08,455 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [142/200], Loss: 0.7766

2026-04-17 11:02:08,455 skrec.estimator.sequential.sasrec_estimator INFO Epoch [142/200], Loss: 0.7766

2026-04-17 11:02:14,926 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [143/200], Loss: 0.7762

2026-04-17 11:02:14,926 skrec.estimator.sequential.sasrec_estimator INFO Epoch [143/200], Loss: 0.7762

2026-04-17 11:02:21,544 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [144/200], Loss: 0.7760

2026-04-17 11:02:21,544 skrec.estimator.sequential.sasrec_estimator INFO Epoch [144/200], Loss: 0.7760

2026-04-17 11:02:28,042 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [145/200], Loss: 0.7768

2026-04-17 11:02:28,042 skrec.estimator.sequential.sasrec_estimator INFO Epoch [145/200], Loss: 0.7768

2026-04-17 11:02:34,718 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [146/200], Loss: 0.7761

2026-04-17 11:02:34,718 skrec.estimator.sequential.sasrec_estimator INFO Epoch [146/200], Loss: 0.7761

2026-04-17 11:02:41,171 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [147/200], Loss: 0.7756

2026-04-17 11:02:41,171 skrec.estimator.sequential.sasrec_estimator INFO Epoch [147/200], Loss: 0.7756

2026-04-17 11:02:47,652 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [148/200], Loss: 0.7751

2026-04-17 11:02:47,652 skrec.estimator.sequential.sasrec_estimator INFO Epoch [148/200], Loss: 0.7751

2026-04-17 11:02:54,039 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [149/200], Loss: 0.7762

2026-04-17 11:02:54,039 skrec.estimator.sequential.sasrec_estimator INFO Epoch [149/200], Loss: 0.7762

2026-04-17 11:03:00,461 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [150/200], Loss: 0.7754

2026-04-17 11:03:00,461 skrec.estimator.sequential.sasrec_estimator INFO Epoch [150/200], Loss: 0.7754

2026-04-17 11:03:06,924 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [151/200], Loss: 0.7754

2026-04-17 11:03:06,924 skrec.estimator.sequential.sasrec_estimator INFO Epoch [151/200], Loss: 0.7754

2026-04-17 11:03:13,464 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [152/200], Loss: 0.7752

2026-04-17 11:03:13,464 skrec.estimator.sequential.sasrec_estimator INFO Epoch [152/200], Loss: 0.7752

2026-04-17 11:03:20,022 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [153/200], Loss: 0.7761

2026-04-17 11:03:20,022 skrec.estimator.sequential.sasrec_estimator INFO Epoch [153/200], Loss: 0.7761

2026-04-17 11:03:26,473 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [154/200], Loss: 0.7741

2026-04-17 11:03:26,473 skrec.estimator.sequential.sasrec_estimator INFO Epoch [154/200], Loss: 0.7741

2026-04-17 11:03:33,002 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [155/200], Loss: 0.7741

2026-04-17 11:03:33,002 skrec.estimator.sequential.sasrec_estimator INFO Epoch [155/200], Loss: 0.7741

2026-04-17 11:03:39,599 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [156/200], Loss: 0.7737

2026-04-17 11:03:39,599 skrec.estimator.sequential.sasrec_estimator INFO Epoch [156/200], Loss: 0.7737

2026-04-17 11:03:46,121 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [157/200], Loss: 0.7745

2026-04-17 11:03:46,121 skrec.estimator.sequential.sasrec_estimator INFO Epoch [157/200], Loss: 0.7745

2026-04-17 11:03:52,604 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [158/200], Loss: 0.7745

2026-04-17 11:03:52,604 skrec.estimator.sequential.sasrec_estimator INFO Epoch [158/200], Loss: 0.7745

2026-04-17 11:03:59,210 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [159/200], Loss: 0.7752

2026-04-17 11:03:59,210 skrec.estimator.sequential.sasrec_estimator INFO Epoch [159/200], Loss: 0.7752

2026-04-17 11:04:05,734 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [160/200], Loss: 0.7744

2026-04-17 11:04:05,734 skrec.estimator.sequential.sasrec_estimator INFO Epoch [160/200], Loss: 0.7744

2026-04-17 11:04:12,279 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [161/200], Loss: 0.7736

2026-04-17 11:04:12,279 skrec.estimator.sequential.sasrec_estimator INFO Epoch [161/200], Loss: 0.7736

2026-04-17 11:04:18,870 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [162/200], Loss: 0.7734

2026-04-17 11:04:18,870 skrec.estimator.sequential.sasrec_estimator INFO Epoch [162/200], Loss: 0.7734

2026-04-17 11:04:25,373 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [163/200], Loss: 0.7741

2026-04-17 11:04:25,373 skrec.estimator.sequential.sasrec_estimator INFO Epoch [163/200], Loss: 0.7741

2026-04-17 11:04:31,885 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [164/200], Loss: 0.7748

2026-04-17 11:04:31,885 skrec.estimator.sequential.sasrec_estimator INFO Epoch [164/200], Loss: 0.7748

2026-04-17 11:04:38,395 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [165/200], Loss: 0.7736

2026-04-17 11:04:38,395 skrec.estimator.sequential.sasrec_estimator INFO Epoch [165/200], Loss: 0.7736

2026-04-17 11:04:44,861 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [166/200], Loss: 0.7746

2026-04-17 11:04:44,861 skrec.estimator.sequential.sasrec_estimator INFO Epoch [166/200], Loss: 0.7746

2026-04-17 11:04:51,219 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [167/200], Loss: 0.7740

2026-04-17 11:04:51,219 skrec.estimator.sequential.sasrec_estimator INFO Epoch [167/200], Loss: 0.7740

2026-04-17 11:04:57,594 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [168/200], Loss: 0.7728

2026-04-17 11:04:57,594 skrec.estimator.sequential.sasrec_estimator INFO Epoch [168/200], Loss: 0.7728

2026-04-17 11:05:04,087 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [169/200], Loss: 0.7741

2026-04-17 11:05:04,087 skrec.estimator.sequential.sasrec_estimator INFO Epoch [169/200], Loss: 0.7741

2026-04-17 11:05:10,524 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [170/200], Loss: 0.7732

2026-04-17 11:05:10,524 skrec.estimator.sequential.sasrec_estimator INFO Epoch [170/200], Loss: 0.7732

2026-04-17 11:06:35,862 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [171/200], Loss: 0.7747

2026-04-17 11:06:35,862 skrec.estimator.sequential.sasrec_estimator INFO Epoch [171/200], Loss: 0.7747

2026-04-17 11:06:42,399 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [172/200], Loss: 0.7736

2026-04-17 11:06:42,399 skrec.estimator.sequential.sasrec_estimator INFO Epoch [172/200], Loss: 0.7736

2026-04-17 11:06:49,001 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [173/200], Loss: 0.7724

2026-04-17 11:06:49,001 skrec.estimator.sequential.sasrec_estimator INFO Epoch [173/200], Loss: 0.7724

2026-04-17 11:06:55,643 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [174/200], Loss: 0.7732

2026-04-17 11:06:55,643 skrec.estimator.sequential.sasrec_estimator INFO Epoch [174/200], Loss: 0.7732

2026-04-17 11:07:02,113 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [175/200], Loss: 0.7730

2026-04-17 11:07:02,113 skrec.estimator.sequential.sasrec_estimator INFO Epoch [175/200], Loss: 0.7730

2026-04-17 11:07:22,884 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [176/200], Loss: 0.7726

2026-04-17 11:07:22,884 skrec.estimator.sequential.sasrec_estimator INFO Epoch [176/200], Loss: 0.7726

2026-04-17 11:07:29,433 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [177/200], Loss: 0.7725

2026-04-17 11:07:29,433 skrec.estimator.sequential.sasrec_estimator INFO Epoch [177/200], Loss: 0.7725

2026-04-17 11:07:36,160 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [178/200], Loss: 0.7728

2026-04-17 11:07:36,160 skrec.estimator.sequential.sasrec_estimator INFO Epoch [178/200], Loss: 0.7728

2026-04-17 11:07:42,781 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [179/200], Loss: 0.7734

2026-04-17 11:07:42,781 skrec.estimator.sequential.sasrec_estimator INFO Epoch [179/200], Loss: 0.7734

2026-04-17 11:07:49,425 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [180/200], Loss: 0.7726

2026-04-17 11:07:49,425 skrec.estimator.sequential.sasrec_estimator INFO Epoch [180/200], Loss: 0.7726

2026-04-17 11:07:55,938 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [181/200], Loss: 0.7720

2026-04-17 11:07:55,938 skrec.estimator.sequential.sasrec_estimator INFO Epoch [181/200], Loss: 0.7720

2026-04-17 11:08:02,440 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [182/200], Loss: 0.7727

2026-04-17 11:08:02,440 skrec.estimator.sequential.sasrec_estimator INFO Epoch [182/200], Loss: 0.7727

2026-04-17 11:08:09,054 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [183/200], Loss: 0.7733

2026-04-17 11:08:09,054 skrec.estimator.sequential.sasrec_estimator INFO Epoch [183/200], Loss: 0.7733

2026-04-17 11:08:15,489 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [184/200], Loss: 0.7731

2026-04-17 11:08:15,489 skrec.estimator.sequential.sasrec_estimator INFO Epoch [184/200], Loss: 0.7731

2026-04-17 11:08:21,928 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [185/200], Loss: 0.7722

2026-04-17 11:08:21,928 skrec.estimator.sequential.sasrec_estimator INFO Epoch [185/200], Loss: 0.7722

2026-04-17 11:08:28,570 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [186/200], Loss: 0.7722

2026-04-17 11:08:28,570 skrec.estimator.sequential.sasrec_estimator INFO Epoch [186/200], Loss: 0.7722

2026-04-17 11:08:35,116 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [187/200], Loss: 0.7731

2026-04-17 11:08:35,116 skrec.estimator.sequential.sasrec_estimator INFO Epoch [187/200], Loss: 0.7731

2026-04-17 11:08:41,692 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [188/200], Loss: 0.7720

2026-04-17 11:08:41,692 skrec.estimator.sequential.sasrec_estimator INFO Epoch [188/200], Loss: 0.7720

2026-04-17 11:08:48,207 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [189/200], Loss: 0.7717

2026-04-17 11:08:48,207 skrec.estimator.sequential.sasrec_estimator INFO Epoch [189/200], Loss: 0.7717

2026-04-17 11:08:54,775 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [190/200], Loss: 0.7724

2026-04-17 11:08:54,775 skrec.estimator.sequential.sasrec_estimator INFO Epoch [190/200], Loss: 0.7724

2026-04-17 11:09:01,246 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [191/200], Loss: 0.7722

2026-04-17 11:09:01,246 skrec.estimator.sequential.sasrec_estimator INFO Epoch [191/200], Loss: 0.7722

2026-04-17 11:09:07,592 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [192/200], Loss: 0.7709

2026-04-17 11:09:07,592 skrec.estimator.sequential.sasrec_estimator INFO Epoch [192/200], Loss: 0.7709

2026-04-17 11:09:13,942 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [193/200], Loss: 0.7716

2026-04-17 11:09:13,942 skrec.estimator.sequential.sasrec_estimator INFO Epoch [193/200], Loss: 0.7716

2026-04-17 11:09:20,339 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [194/200], Loss: 0.7728

2026-04-17 11:09:20,339 skrec.estimator.sequential.sasrec_estimator INFO Epoch [194/200], Loss: 0.7728

2026-04-17 11:09:26,855 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [195/200], Loss: 0.7713

2026-04-17 11:09:26,855 skrec.estimator.sequential.sasrec_estimator INFO Epoch [195/200], Loss: 0.7713

2026-04-17 11:09:33,451 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [196/200], Loss: 0.7713

2026-04-17 11:09:33,451 skrec.estimator.sequential.sasrec_estimator INFO Epoch [196/200], Loss: 0.7713

2026-04-17 11:09:39,943 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [197/200], Loss: 0.7714

2026-04-17 11:09:39,943 skrec.estimator.sequential.sasrec_estimator INFO Epoch [197/200], Loss: 0.7714

2026-04-17 11:09:46,609 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [198/200], Loss: 0.7706

2026-04-17 11:09:46,609 skrec.estimator.sequential.sasrec_estimator INFO Epoch [198/200], Loss: 0.7706

2026-04-17 11:09:53,257 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [199/200], Loss: 0.7706

2026-04-17 11:09:53,257 skrec.estimator.sequential.sasrec_estimator INFO Epoch [199/200], Loss: 0.7706

2026-04-17 11:09:59,738 - skrec.estimator.sequential.sasrec_estimator - INFO Epoch [200/200], Loss: 0.7718

2026-04-17 11:09:59,738 skrec.estimator.sequential.sasrec_estimator INFO Epoch [200/200], Loss: 0.7718

Training complete.

## 8. Evaluate: HR@10 and NDCG@10

Same leave-last-out evaluation as notebook 1. The held-out item may have any
rating (1–5) — we check only whether it appears in the top-10, not whether it
was liked. This tests how well the model predicts the user's *next action*.

User order is anchored to `_build_sequences` output to guarantee row alignment
with `recommend()`.

In [9]:
rng = np.random.default_rng(42)
all_item_ids = np.array(list(scorer.item_names))

known_items = set(scorer.item_names)
eval_test_df = test_df[test_df["ITEM_ID"].isin(known_items)].copy()
eval_users = set(eval_test_df["USER_ID"])

# Evaluation history: all interactions EXCEPT the test item.
# The model's last-position representation was trained to predict the test item
# from exactly this context.
eval_history_df = all_except_test_df[all_except_test_df["USER_ID"].isin(eval_users)].copy()
eval_history_df = eval_history_df.sort_values(["USER_ID", "TIMESTAMP"]).reset_index(drop=True)

print(f"Evaluating {len(eval_users):,} users (sampled ranking: 1 positive + 100 negatives)...")

sequences_df = recommender._build_sequences(eval_history_df)
user_order = sequences_df["USER_ID"].tolist()

# Get all-item scores once: (num_users, num_items)
all_scores = recommender.scorer.estimator.predict_proba_with_embeddings(interactions=sequences_df)
item_name_to_idx = {name: i for i, name in enumerate(scorer.item_names)}

gt_lookup = eval_test_df.set_index("USER_ID")["ITEM_ID"].to_dict()
user_items = interactions.groupby("USER_ID")["ITEM_ID"].apply(set).to_dict()

TOP_K = 10
N_NEGATIVES = 100

hits, ndcgs = [], []
for i, user_id in enumerate(user_order):
    test_item = gt_lookup.get(user_id)
    if test_item is None:
        continue

    seen = user_items.get(user_id, set())
    candidates = all_item_ids[~np.isin(all_item_ids, list(seen))]
    neg_sample = rng.choice(candidates, size=min(N_NEGATIVES, len(candidates)), replace=False)

    candidate_ids = [test_item] + list(neg_sample)
    candidate_idxs = [item_name_to_idx[c] for c in candidate_ids if c in item_name_to_idx]
    candidate_scores = all_scores[i, candidate_idxs]

    test_score = all_scores[i, item_name_to_idx[test_item]]
    rank = int((candidate_scores > test_score).sum()) + 1

    if rank <= TOP_K:
        hits.append(1)
        ndcgs.append(1.0 / np.log2(rank + 1))
    else:
        hits.append(0)
        ndcgs.append(0.0)

print(f"\n{'=' * 40}")
print(f"Evaluation: 1 positive + {N_NEGATIVES} random negatives")
print(f"HR@{TOP_K}   : {np.mean(hits):.4f}")
print(f"NDCG@{TOP_K} : {np.mean(ndcgs):.4f}")
print(f"Users evaluated: {len(hits):,}")
print(f"{'=' * 40}")

Evaluating 6,040 users (sampled ranking: 1 positive + 100 negatives)...

2026-04-17 11:10:00,204 - skrec.recommender.sequential.sequential_recommender - INFO Built sequences for 6040 users (max_len=200, has_outcome=True).

2026-04-17 11:10:00,204 skrec.recommender.sequential.sequential_recommender INFO Built sequences for 6040 users (max_len=200, has_outcome=True).

========================================
Evaluation: 1 positive + 100 random negatives
HR@10   : 0.8613
NDCG@10 : 0.5751
Users evaluated: 6,040
========================================

## 9. Breakdown: HR@10 by Test Item Rating

Since the test item has a known rating, we can check whether the model is
better at predicting items the user *liked* versus items they *disliked*.
A well-trained model should show higher HR@10 for 4–5 star test items because
those items are more similar to the items already in the user's high-rated sequence.

In [10]:
gt_rating_lookup = eval_test_df.set_index("USER_ID")["OUTCOME"].to_dict()

records = []
for i, user_id in enumerate(user_order):
    test_item = gt_lookup.get(user_id)
    test_rating = gt_rating_lookup.get(user_id)
    if test_item is None:
        continue
    seen = user_items.get(user_id, set())
    candidates = all_item_ids[~np.isin(all_item_ids, list(seen))]
    neg_sample = rng.choice(candidates, size=min(N_NEGATIVES, len(candidates)), replace=False)
    candidate_ids = [test_item] + list(neg_sample)
    candidate_idxs = [item_name_to_idx[c] for c in candidate_ids if c in item_name_to_idx]
    candidate_scores = all_scores[i, candidate_idxs]
    test_score = all_scores[i, item_name_to_idx[test_item]]
    rank = int((candidate_scores > test_score).sum()) + 1
    hit = int(rank <= TOP_K)
    ndcg = (1.0 / np.log2(rank + 1)) if hit else 0.0
    records.append({"test_rating": int(test_rating), "hit": hit, "ndcg": ndcg})

breakdown = (
    pd.DataFrame(records)
    .groupby("test_rating")
    .agg(
        n_users=("hit", "count"),
        HR10=("hit", "mean"),
        NDCG10=("ndcg", "mean"),
    )
    .round(4)
)

print("HR@10 and NDCG@10 broken down by test item rating (sampled eval):")
print(breakdown.to_string())

HR@10 and NDCG@10 broken down by test item rating (sampled eval):
             n_users    HR10  NDCG10
test_rating
0               4467  0.8464  0.5511
1               1573  0.9072  0.6626

## 10. Sample Recommendations

Show top-10 recommendations for a few users alongside their held-out test item
and its rating.

In [11]:
movie_title = movies.set_index(movies["MovieID"].astype(str))["Title"].to_dict()
gt_rating_lookup = eval_test_df.set_index("USER_ID")["OUTCOME"].to_dict()

# Use all-except-test history (same as evaluation) so sequences are consistent
top_k_recs = recommender.recommend(interactions=eval_history_df, top_k=TOP_K)

for user_id in user_order[:5]:
    idx = user_order.index(user_id)
    recs = list(top_k_recs[idx])
    test_item = gt_lookup.get(user_id, "?")
    test_rating = gt_rating_lookup.get(user_id, "?")
    hit = "HIT" if test_item in recs else "MISS"
    print(
        f"\nUser {user_id}  |  Test item: {movie_title.get(test_item, test_item)} (rated {test_rating:.0f}/5)  [{hit}]"
    )
    print("  Top-10 (full-item ranking):")
    for rank, item_id in enumerate(recs, 1):
        marker = " <-- TEST ITEM" if item_id == test_item else ""
        print(f"    {rank:2}. {movie_title.get(item_id, item_id)}{marker}")

2026-04-17 11:10:03,820 - skrec.recommender.sequential.sequential_recommender - INFO Built sequences for 6040 users (max_len=200, has_outcome=True).

2026-04-17 11:10:03,820 skrec.recommender.sequential.sequential_recommender INFO Built sequences for 6040 users (max_len=200, has_outcome=True).

User 1  |  Test item: Pocahontas (1995) (rated 1/5)  [MISS]
  Top-10 (full-item ranking):
     1. Little Princess, A (1995)
     2. Beauty and the Beast (1991)
     3. Lion King, The (1994)
     4. Mulan (1998)
     5. Fantasia 2000 (1999)
     6. Toy Story (1995)
     7. Bug's Life, A (1998)
     8. Secret Garden, The (1993)
     9. Tarzan (1999)
    10. Balto (1995)

User 10  |  Test item: Hero (1992) (rated 1/5)  [MISS]
  Top-10 (full-item ranking):
     1. It's a Wonderful Life (1946)
     2. Schindler's List (1993)
     3. To Kill a Mockingbird (1962)
     4. Seven Samurai (The Magnificent Seven) (Shichinin no samurai) (1954)
     5. Grapes of Wrath, The (1940)
     6. Vertigo (1958)
     7. Bridge on the River Kwai, The (1957)
     8. North by Northwest (1959)
     9. Lawrence of Arabia (1962)
    10. 12 Angry Men (1957)

User 100  |  Test item: Apocalypse Now (1979) (rated 0/5)  [MISS]
  Top-10 (full-item ranking):
     1. Shawshank Redemption, The (1994)
     2. October Sky (1999)
     3. Sixth Sense, The (1999)
     4. Schindler's List (1993)
     5. Good Will Hunting (1997)
     6. Life Is Beautiful (La Vita è bella) (1997)
     7. To Live (Huozhe) (1994)
     8. Sling Blade (1996)
     9. Some Folks Call It a Sling Blade (1993)
    10. American Beauty (1999)

User 1000  |  Test item: Streetcar Named Desire, A (1951) (rated 1/5)  [MISS]
  Top-10 (full-item ranking):
     1. Schindler's List (1993)
     2. Shawshank Redemption, The (1994)
     3. Sixth Sense, The (1999)
     4. It's a Wonderful Life (1946)
     5. October Sky (1999)
     6. Breaking Away (1979)
     7. One Flew Over the Cuckoo's Nest (1975)
     8. Right Stuff, The (1983)
     9. Good Will Hunting (1997)
    10. To Kill a Mockingbird (1962)

User 1001  |  Test item: Austin Powers: The Spy Who Shagged Me (1999) (rated 0/5)  [MISS]
  Top-10 (full-item ranking):
     1. Butterfly (La Lengua de las Mariposas) (2000)
     2. Broken Hearts Club, The (2000)
     3. To Live (Huozhe) (1994)
     4. Golden Bowl, The (2000)
     5. Requiem for a Dream (2000)
     6. King of the Hill (1993)
     7. Following (1998)
     8. Goya in Bordeaux (Goya en Bodeos) (1999)
     9. Safe Men (1998)
    10. Suture (1993)